export const APP_META = Object.freeze({
  name: "Diagnóstico de Incentivos e Funding",
  brand: "MonyU",
  rulesVersion: "1.0.2",
  rulesUpdatedAt: "2026-07-10",
  storageKey: "monyu-diagnostico-v2",
});

export const STATUS = Object.freeze({
  AVAILABLE: "APROVEITAVEL_AGORA",
  VALIDATE: "POTENCIAL_VALIDAR",
  PREPARE: "PREPARAR",
  OPTIMIZE: "JA_USA_OTIMIZAR",
  NOT_RELEVANT: "NAO_RELEVANTE",
  BLOCKED: "BLOQUEADO",
});

export const STATUS_COPY = Object.freeze({
  [STATUS.AVAILABLE]: { label: "Pode aproveitar agora", tone: "positive" },
  [STATUS.VALIDATE]: { label: "Tem potencial, mas precisa validar", tone: "attention" },
  [STATUS.PREPARE]: { label: "Pode se preparar para acessar", tone: "neutral" },
  [STATUS.OPTIMIZE]: { label: "Pode otimizar o uso", tone: "positive" },
  [STATUS.NOT_RELEVANT]: { label: "Não é indicado agora", tone: "muted" },
  [STATUS.BLOCKED]: { label: "Há um impeditivo agora", tone: "danger" },
});

export const STEPS = Object.freeze([
  { id: 1, name: "Direcionamento" },
  { id: 2, name: "Estrutura da empresa" },
  { id: 3, name: "Perfil de inovação" },
  { id: 4, name: "Capacidade e evidências" },
  { id: 5, name: "Trilhas relevantes" },
  { id: 6, name: "Resultado" },
]);

export const LEGAL_SOURCES = Object.freeze({
  LEIBEM: {
    label: "Lei nº 11.196/2005 e Decreto nº 5.798/2006",
    url: "https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2005/lei/L11196compilado.htm",
  },
  LEIBEM_ICT_19A: {
    label: "Lei nº 11.196/2005, art. 19-A",
    url: "https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2005/lei/L11196compilado.htm",
  },
  LEITIC: {
    label: "Lei nº 8.248/1991 e legislação correlata",
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8248.htm",
  },
  RENUCIA_TECNOLOGIA: {
    label: "Lei nº 9.249/1995, art. 13, § 2º, II e III, e IN SRF nº 87/1996",
    url: "https://www.planalto.gov.br/ccivil_03/leis/l9249.htm",
  },
  STARTUPLC182: {
    label: "Lei Complementar nº 182/2021",
    url: "https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp182.htm",
  },
});

export const PARAMETERS = Object.freeze({
  effectiveFrom: "2026-07-10",
  source: "Textos legais oficiais indicados em LEGAL_SOURCES; revisão profissional recomendada antes de uso fiscal.",
  taxRate: 0.34,
  leiBem: {
    baseExclusion: 0.6,
    researcherIncreaseHigh: 0.2,
    intellectualPropertyIncrease: 0.2,
    maxExclusion: 1,
  },
  leiBemIct19A: {
    conservativeExclusion: 0.5,
  },
  renunciaTecnologia: {
    educationResearchOperatingProfitLimit: 0.015,
    workerCommunityOperatingProfitLimit: 0.02,
    irpjRate: 0.15,
    irpjAdditionalRate: 0.1,
    irpjAdditionalAnnualThreshold: 240000,
    csllRate: 0.09,
  },
  embrapii: {
    cofundingMin: null,
    cofundingMax: null,
  },
  ranges: {
    innovationSpend: {
      ate_50k: { min: 0, max: 50000, label: "Até R$ 50 mil" },
      de_50k_200k: { min: 50000, max: 200000, label: "R$ 50 mil a R$ 200 mil" },
      de_200k_1m: { min: 200000, max: 1000000, label: "R$ 200 mil a R$ 1 mi" },
      de_1m_5m: { min: 1000000, max: 5000000, label: "R$ 1 mi a R$ 5 mi" },
      acima_5m: { min: 5000000, max: null, label: "Acima de R$ 5 mi" },
    },
    ictProject: {
      ate_50k: { min: 0, max: 50000, label: "Até R$ 50 mil" },
      de_50k_200k: { min: 50000, max: 200000, label: "R$ 50 mil a R$ 200 mil" },
      de_200k_1m: { min: 200000, max: 1000000, label: "R$ 200 mil a R$ 1 mi" },
      de_1m_5m: { min: 1000000, max: 5000000, label: "R$ 1 mi a R$ 5 mi" },
      acima_5m: { min: 5000000, max: null, label: "Acima de R$ 5 mi" },
    },
    technologyOperation: {
      ate_50k: { min: 0, max: 50000, label: "Até R$ 50 mil" },
      de_50k_200k: { min: 50000, max: 200000, label: "R$ 50 mil a R$ 200 mil" },
      de_200k_1m: { min: 200000, max: 1000000, label: "R$ 200 mil a R$ 1 mi" },
      de_1m_5m: { min: 1000000, max: 5000000, label: "R$ 1 mi a R$ 5 mi" },
      acima_5m: { min: 5000000, max: null, label: "Acima de R$ 5 mi" },
    },
    operatingProfit: {
      ate_1m: { min: 0, max: 1000000, label: "Até R$ 1 milhão" },
      de_1m_10m: { min: 1000000, max: 10000000, label: "R$ 1 milhão a R$ 10 milhões" },
      de_10m_50m: { min: 10000000, max: 50000000, label: "R$ 10 milhões a R$ 50 milhões" },
      de_50m_200m: { min: 50000000, max: 200000000, label: "R$ 50 milhões a R$ 200 milhões" },
      acima_200m: { min: 200000000, max: null, label: "Acima de R$ 200 milhões" },
    },
    ticRevenue: {
      ate_500k: { min: 0, max: 500000, label: "Até R$ 500 mil" },
      de_500k_5m: { min: 500000, max: 5000000, label: "R$ 500 mil a R$ 5 mi" },
      de_5m_50m: { min: 5000000, max: 50000000, label: "R$ 5 mi a R$ 50 mi" },
      acima_50m: { min: 50000000, max: null, label: "Acima de R$ 50 mi" },
    },
  },
});

const choice = (value, label, detail, symbol, tone = "pink") => ({
  value,
  label,
  detail,
  symbol,
  tone,
});

export const QUESTION_BANK = Object.freeze([
  {
    id: "objetivo_principal",
    order: 1,
    stage: 1,
    section: "COMEÇAMOS PELO ESSENCIAL",
    title: "O que a empresa mais quer resolver agora?",
    help: "Escolha a prioridade que melhor representa este momento.",
    type: "single",
    category: "priorizacao",
    condition: "always",
    options: [
      choice("reduzir_impostos", "Reduzir impostos", "Encontrar incentivos fiscais aplicáveis", "R$"),
      choice("buscar_funding", "Buscar dinheiro para inovar ou crescer", "Mapear fomento e recursos não reembolsáveis", "+", "orange"),
      choice("financiar_expansao", "Financiar máquinas, equipamentos ou expansão", "Avaliar crédito e linhas de financiamento", "↗", "yellow"),
      choice("atrair_investidor", "Atrair investidor", "Entender caminhos de estruturação e capital", "◆", "orange"),
      choice("apoiar_projetos", "Apoiar educação, pesquisa ou impacto social", "Avaliar Renúncia Fiscal em Tecnologia", "◌", "yellow"),
      choice("nao_sei", "Ainda não sei", "Vamos identificar as oportunidades com você", "?"),
    ],
  },
  {
    id: "regime_tributario",
    order: 2,
    stage: 2,
    section: "ESTRUTURA DA EMPRESA",
    title: "Como a empresa paga seus impostos hoje?",
    help: "Esta resposta define quais incentivos podem ser aproveitados agora.",
    type: "single",
    category: "corte",
    condition: "always",
    options: [
      choice("simples_nacional", "Simples Nacional", "Regime simplificado para pequenos negócios", "S"),
      choice("lucro_presumido", "Lucro Presumido", "Tributação baseada em uma margem presumida", "LP", "orange"),
      choice("lucro_real", "Lucro Real", "Tributação baseada no lucro efetivamente apurado", "LR", "yellow"),
      choice("nao_sei", "Não sei", "Continuaremos com uma estimativa orientada", "?"),
    ],
  },
  {
    id: "faturamento_faixa",
    order: 3,
    stage: 2,
    section: "ESTRUTURA DA EMPRESA",
    title: "Qual é o faturamento anual aproximado da empresa?",
    help: "Uma faixa é suficiente. Não pedimos números exatos nesta etapa.",
    type: "single",
    category: "corte",
    condition: "always",
    options: [
      choice("ate_360k", "Até R$ 360 mil", "Faixa de microempresa", "360k"),
      choice("de_360k_48m", "R$ 360 mil a R$ 4,8 milhões", "Faixa de pequena empresa", "4,8M", "orange"),
      choice("de_48m_16m", "R$ 4,8 milhões a R$ 16 milhões", "Faixa relevante para startups", "16M", "yellow"),
      choice("de_16m_300m", "R$ 16 milhões a R$ 300 milhões", "Empresa em escala", "300M", "orange"),
      choice("acima_300m", "Acima de R$ 300 milhões", "Grande empresa", "300+", "yellow"),
      choice("nao_sei", "Não sei", "Seguimos com a melhor estimativa possível", "?"),
    ],
  },
  {
    id: "tempo_existencia",
    order: 4,
    stage: 2,
    section: "ESTRUTURA DA EMPRESA",
    title: "Há quanto tempo a empresa existe?",
    help: "Isso ajuda a identificar caminhos voltados a negócios inovadores em formação.",
    type: "single",
    category: "corte",
    condition: "always",
    options: [
      choice("menos_2", "Menos de 2 anos", "Negócio em fase inicial", "2"),
      choice("de_2_5", "De 2 a 5 anos", "Negócio em consolidação", "5", "orange"),
      choice("de_5_10", "De 5 a 10 anos", "Negócio em expansão", "10", "yellow"),
      choice("mais_10", "Mais de 10 anos", "Empresa madura", "10+", "orange"),
      choice("nao_sei", "Não sei", "Seguimos sem usar esse critério", "?"),
    ],
  },
  {
    id: "setor",
    order: 5,
    stage: 2,
    section: "ESTRUTURA DA EMPRESA",
    title: "Qual é o principal setor da empresa?",
    help: "Escolha o setor que mais representa a operação e a receita atual.",
    type: "single",
    category: "corte",
    condition: "always",
    options: [
      choice("tecnologia_software", "Tecnologia ou software", "Produtos, plataformas ou serviços digitais", "<>"),
      choice("eletronicos_hardware", "Eletrônicos ou hardware", "Equipamentos, componentes e dispositivos", "HW", "orange"),
      choice("industria", "Indústria geral", "Transformação ou produção", "IN", "yellow"),
      choice("servicos", "Serviços", "Operações e atendimento especializado", "SV", "orange"),
      choice("saude", "Saúde", "Serviços, produtos ou tecnologia em saúde", "+", "yellow"),
      choice("agro", "Agro", "Produção, insumos ou agrotecnologia", "AG", "orange"),
      choice("financeiro", "Financeiro", "Serviços financeiros, seguros ou fintech", "R$", "yellow"),
      choice("varejo", "Varejo ou comércio", "Comércio físico ou digital", "VC", "orange"),
      choice("semicondutores", "Semicondutores", "Chips, displays ou cadeia associada", "SC", "yellow"),
      choice("automotivo_mobilidade", "Automotivo ou mobilidade", "Veículos, autopeças ou mobilidade", "MV", "orange"),
      choice("outro", "Outro", "Setor não listado", "…"),
    ],
  },
  {
    id: "regularidade_fiscal",
    order: 6,
    stage: 2,
    section: "ESTRUTURA DA EMPRESA",
    title: "A empresa está em dia com os impostos federais ou consegue regularizar rapidamente?",
    help: "A regularidade costuma ser exigida para benefícios e linhas de financiamento.",
    type: "single",
    category: "risco",
    condition: "always",
    options: [
      choice("sim", "Sim", "A situação está regular", "✓", "yellow"),
      choice("nao", "Não", "Há pendências relevantes", "!", "orange"),
      choice("nao_sei", "Não sei", "Precisamos confirmar", "?"),
      choice("parcelamento_em_dia", "Existe parcelamento em dia", "A situação pode ser comprovada", "≡", "yellow"),
    ],
  },
  {
    id: "atividades_inovacao",
    order: 7,
    stage: 3,
    section: "PERFIL DE INOVAÇÃO",
    title: "A empresa faz alguma destas atividades?",
    help: "Marque todas as que se aplicam. Não é preciso usar linguagem técnica.",
    type: "multiple",
    category: "corte",
    condition: "always",
    exclusiveValues: ["nenhuma", "nao_sei"],
    options: [
      choice("produto_fisico", "Cria produto físico", "Produtos, equipamentos ou componentes próprios", "PF", "yellow"),
      choice("software_proprio", "Desenvolve software, sistema ou plataforma própria", "Soluções digitais que a empresa cria ou evolui", "<>"),
      choice("melhoria_processo", "Melhora processo, fórmula, método ou operação", "Testes para fazer melhor, mais rápido ou com menos custo", "↗", "orange"),
      choice("testes_prototipos", "Faz testes, protótipos ou experimentos", "Validação técnica antes de escalar", "⌁", "yellow"),
      choice("parceria_ict", "Trabalha com universidade, instituto ou laboratório", "Desenvolvimento com parceiro técnico", "UT", "orange"),
      choice("nenhuma", "Nenhuma dessas", "Não identifico atividades desse tipo agora", "—"),
      choice("nao_sei", "Não sei", "Quero ajuda para reconhecer essas atividades", "?"),
    ],
  },
  {
    id: "inovacao_informal",
    order: 8,
    stage: 3,
    section: "UM OLHAR MAIS PRÓXIMO",
    title: "Mesmo informalmente, a empresa testa novas formas de produzir, vender, atender ou reduzir custos?",
    help: "Muitas empresas inovam sem chamar isso de inovação. Esta pergunta evita descartar uma oportunidade cedo demais.",
    type: "single",
    category: "corte",
    condition: "needs_informal_check",
    options: [
      choice("com_frequencia", "Sim, com frequência", "Esse tipo de melhoria faz parte da rotina", "✓", "yellow"),
      choice("as_vezes", "Às vezes", "Acontece em iniciativas específicas", "~", "orange"),
      choice("nao", "Não", "Não identifico isso agora", "—"),
      choice("nao_sei", "Não sei", "Precisamos conversar melhor sobre o dia a dia", "?"),
    ],
  },
  {
    id: "lucro_ou_imposto",
    order: 9,
    stage: 4,
    section: "CAPACIDADE FISCAL",
    title: "No último ano, a empresa teve lucro tributável ou imposto relevante a pagar?",
    help: "É uma referência para saber se um benefício fiscal pode gerar efeito imediato.",
    type: "single",
    category: "calculo",
    condition: "innovation_positive",
    options: [
      choice("sim", "Sim", "Há lucro ou imposto relevante a pagar", "✓", "yellow"),
      choice("prejuizo", "Não, teve prejuízo", "O benefício pode não virar economia agora", "—", "orange"),
      choice("nao_sei", "Não sei", "Precisamos confirmar com a contabilidade", "?"),
      choice("validar_contador", "Prefiro validar com o contador", "Seguiremos com uma estimativa prudente", "CT", "orange"),
    ],
  },
  {
    id: "gasto_inovacao",
    order: 10,
    stage: 4,
    section: "CAPACIDADE FISCAL",
    title: "Quanto a empresa gasta por ano com criação, melhoria, desenvolvimento, testes ou projetos técnicos?",
    help: "Considere pessoas, materiais, testes e outros gastos ligados aos projetos. Uma faixa basta.",
    type: "single",
    category: "calculo",
    condition: "innovation_positive",
    options: [
      choice("ate_50k", "Até R$ 50 mil", "Investimento inicial", "50k"),
      choice("de_50k_200k", "R$ 50 mil a R$ 200 mil", "Investimento recorrente", "200k", "orange"),
      choice("de_200k_1m", "R$ 200 mil a R$ 1 milhão", "Investimento relevante", "1M", "yellow"),
      choice("de_1m_5m", "R$ 1 milhão a R$ 5 milhões", "Investimento estruturado", "5M", "orange"),
      choice("acima_5m", "Acima de R$ 5 milhões", "Investimento de grande porte", "5M+", "yellow"),
      choice("nao_sei", "Não sei", "Mostraremos oportunidades sem cálculo financeiro", "?"),
    ],
  },
  {
    id: "maturidade_contabil",
    order: 11,
    stage: 4,
    section: "CAPACIDADE FISCAL",
    title: "A empresa consegue separar esses gastos por projeto ou iniciativa?",
    help: "Não precisa estar perfeito. Queremos entender o nível atual de organização.",
    type: "single",
    category: "risco",
    condition: "innovation_positive",
    options: [
      choice("com_clareza", "Sim, com clareza", "Gastos organizados por projeto ou centro de custo", "✓", "yellow"),
      choice("mais_ou_menos", "Mais ou menos", "Parte dos gastos está identificada", "~", "orange"),
      choice("nao", "Não", "Os gastos estão misturados na operação", "—", "orange"),
      choice("nao_sei", "Não sei", "Precisamos validar com a equipe financeira", "?"),
    ],
  },
  {
    id: "maturidade_documental",
    order: 12,
    stage: 4,
    section: "CAPACIDADE FISCAL",
    title: "A empresa guarda evidências dos projetos, como relatórios, testes, protótipos, atas ou registros?",
    help: "Esses materiais ajudam a demonstrar o que foi desenvolvido e como o dinheiro foi usado.",
    type: "single",
    category: "risco",
    condition: "innovation_positive",
    options: [
      choice("bem_organizado", "Sim, bem organizado", "Documentação disponível e acessível", "✓", "yellow"),
      choice("algumas_evidencias", "Temos algumas evidências", "Há material, mas precisa ser reunido", "~", "orange"),
      choice("quase_nada", "Quase nada", "Ainda não há uma rotina de registro", "—", "orange"),
      choice("nao_sei", "Não sei", "Precisamos confirmar com quem toca os projetos", "?"),
    ],
  },
  {
    id: "uso_leibem",
    order: 13,
    stage: 5,
    section: "TRILHA: LEI DO BEM",
    title: "A empresa já aproveita a Lei do Bem hoje?",
    help: "A Lei do Bem pode reduzir impostos ligados a gastos com desenvolvimento e melhoria tecnológica.",
    type: "single",
    category: "corte",
    condition: "leibem_track",
    options: [
      choice("usa_hoje", "Sim, uso hoje", "Vamos buscar oportunidades de otimização", "✓", "yellow"),
      choice("ja_usei", "Já usei, mas parei", "Vamos entender se é possível retomar", "↺", "orange"),
      choice("nunca_usei", "Nunca usei", "Avaliaremos o potencial atual", "+"),
      choice("nao_sei", "Não sei", "Seguiremos com uma análise prudente", "?"),
    ],
  },
  {
    id: "pesquisadores_equipe",
    order: 14,
    stage: 5,
    section: "TRILHA: LEI DO BEM",
    title: "A empresa tem pessoas contratadas dedicadas a essas atividades de criação ou melhoria?",
    help: "O aumento de pesquisadores pode ampliar o potencial de benefício em alguns casos.",
    type: "single",
    category: "calculo",
    condition: "leibem_track",
    options: [
      choice("nao", "Não", "As atividades não têm uma equipe dedicada", "—"),
      choice("sim_sem_aumento", "Sim, mas sem aumento recente", "Há equipe, mas sem expansão neste ano", "↔", "orange"),
      choice("sim_com_aumento", "Sim, e aumentou a equipe neste ano", "Há crescimento da equipe dedicada", "↑", "yellow"),
      choice("nao_sei", "Não sei", "Precisamos confirmar com RH ou liderança técnica", "?"),
    ],
  },
  {
    id: "propriedade_intelectual",
    order: 15,
    stage: 5,
    section: "TRILHA: LEI DO BEM",
    title: "Algum projeto gerou patente concedida ou cultivar registrado?",
    help: "Algumas situações de propriedade intelectual podem influenciar a estimativa, conforme a lei.",
    type: "single",
    category: "calculo",
    condition: "leibem_track",
    options: [
      choice("patente_concedida", "Sim, patente concedida", "Há patente vinculada a um projeto", "P", "yellow"),
      choice("cultivar_registrado", "Sim, cultivar registrado", "Há registro de cultivar", "C", "yellow"),
      choice("pedido_andamento", "Pedido em andamento", "Ainda sem concessão", "…", "orange"),
      choice("software_registrado", "Apenas software registrado", "Registro de software não aciona esse adicional", "<>"),
      choice("nao", "Não", "Não há patente ou cultivar aplicável", "—"),
      choice("nao_sei", "Não sei", "Precisamos confirmar", "?"),
    ],
  },
  {
    id: "compra_equipamentos",
    order: 16,
    stage: 5,
    section: "TRILHA: LEI DO BEM",
    title: "A empresa comprou máquinas, equipamentos ou instrumentos para usar nesses projetos?",
    help: "Essa informação orienta uma conversa mais precisa sobre os itens que podem ser analisados.",
    type: "single",
    category: "calculo",
    condition: "leibem_track",
    options: [
      choice("sim", "Sim", "Há aquisição ligada a projetos", "✓", "yellow"),
      choice("nao", "Não", "Não houve aquisição relevante", "—"),
      choice("nao_sei", "Não sei", "Precisamos confirmar", "?"),
    ],
  },
  {
    id: "projeto_ict",
    order: 17,
    stage: 5,
    section: "TRILHA: LEI DO BEM",
    title: "A empresa tem projeto formal pago com universidade, instituto de pesquisa ou laboratório?",
    help: "Essa parceria pode abrir uma trilha específica, desde que o projeto esteja corretamente estruturado.",
    type: "single",
    category: "corte",
    condition: "leibem_track",
    options: [
      choice("sim", "Sim", "Existe projeto formal contratado", "✓", "yellow"),
      choice("nao", "Não", "Não há projeto formal desse tipo", "—"),
      choice("negociando", "Estamos negociando", "A parceria está sendo estruturada", "~", "orange"),
      choice("nao_sei", "Não sei", "Precisamos confirmar com a área técnica", "?"),
    ],
  },
  {
    id: "ict_19a_aprovacao",
    order: 18,
    stage: 5,
    section: "TRILHA: PROJETO COM ICT",
    title: "Esse projeto com universidade ou instituto tem aprovação formal ou portaria para uso do incentivo?",
    help: "A aprovação formal é decisiva para transformar esta possibilidade em benefício aplicável.",
    type: "single",
    category: "risco",
    condition: "ict_19a_track",
    options: [
      choice("sim", "Sim", "A aprovação ou portaria está disponível", "✓", "yellow"),
      choice("nao", "Não", "O projeto não tem aprovação formal", "—", "orange"),
      choice("nao_sei", "Não sei", "Precisamos confirmar a documentação", "?"),
      choice("a_estruturar", "Ainda será estruturado", "A parceria está em fase inicial", "~", "orange"),
    ],
  },
  {
    id: "valor_projeto_ict",
    order: 19,
    stage: 5,
    section: "TRILHA: PROJETO COM ICT",
    title: "Qual é o valor aproximado que a empresa paga ou pretende pagar nesse projeto?",
    help: "Use uma faixa aproximada. Ela serve somente para a estimativa preliminar.",
    type: "single",
    category: "calculo",
    condition: "ict_19a_track",
    options: [
      choice("ate_50k", "Até R$ 50 mil", "Projeto inicial", "50k"),
      choice("de_50k_200k", "R$ 50 mil a R$ 200 mil", "Projeto em estruturação", "200k", "orange"),
      choice("de_200k_1m", "R$ 200 mil a R$ 1 milhão", "Projeto relevante", "1M", "yellow"),
      choice("de_1m_5m", "R$ 1 milhão a R$ 5 milhões", "Projeto robusto", "5M", "orange"),
      choice("acima_5m", "Acima de R$ 5 milhões", "Projeto de grande porte", "5M+", "yellow"),
      choice("nao_sei", "Não sei", "Mostraremos a trilha sem cálculo", "?"),
    ],
  },
  {
    id: "atividade_tic_brasil",
    order: 20,
    stage: 5,
    section: "TRILHA: LEI DE TICS",
    title: "A empresa desenvolve ou produz, no Brasil, bens, equipamentos, componentes, hardware, dispositivos conectados ou soluções de tecnologia?",
    help: "Revender produto de terceiros, por si só, não costuma abrir esta trilha.",
    type: "single",
    category: "corte",
    condition: "tic_track",
    options: [
      choice("sim", "Sim", "Há desenvolvimento ou produção no Brasil", "✓", "yellow"),
      choice("nao", "Não", "Não há desenvolvimento ou produção aplicável", "—"),
      choice("revenda", "Apenas revende produtos de terceiros", "Atividade de revenda isolada", "↔", "orange"),
      choice("nao_sei", "Não sei", "Precisamos analisar o produto e a operação", "?"),
    ],
  },
  {
    id: "ncm_ppb",
    order: 21,
    stage: 5,
    section: "TRILHA: LEI DE TICS",
    title: "A empresa conhece o NCM, enquadramento ou processo produtivo do produto tecnológico?",
    help: "Essas informações são importantes para confirmar o enquadramento da Lei de TICs.",
    type: "single",
    category: "risco",
    condition: "tic_track",
    options: [
      choice("ncm_e_ppb", "Sim, temos NCM e PPB mapeados", "Documentação técnica já identificada", "✓", "yellow"),
      choice("somente_ncm", "Temos NCM, mas não PPB", "Parte do mapeamento já existe", "NCM", "orange"),
      choice("nao", "Não", "Ainda não há enquadramento mapeado", "—", "orange"),
      choice("nao_sei", "Não sei", "Precisamos levantar essas informações", "?"),
    ],
  },
  {
    id: "uso_leitic",
    order: 22,
    stage: 5,
    section: "TRILHA: LEI DE TICS",
    title: "A empresa já é habilitada na Lei de Informática ou Lei de TICs?",
    help: "A habilitação atual muda o foco de enquadramento para otimização.",
    type: "single",
    category: "corte",
    condition: "tic_track",
    options: [
      choice("usa_hoje", "Sim, usa hoje", "Vamos procurar melhorias no uso", "✓", "yellow"),
      choice("ja_foi_habilitada", "Já foi habilitada, mas não usa", "Pode haver caminho de retomada", "↺", "orange"),
      choice("nao", "Não", "Avaliaremos a possibilidade de habilitação", "+"),
      choice("nao_sei", "Não sei", "Precisamos confirmar", "?"),
    ],
  },
  {
    id: "faturamento_tic",
    order: 23,
    stage: 5,
    section: "TRILHA: LEI DE TICS",
    title: "Qual é o faturamento anual aproximado com esses produtos ou soluções de tecnologia?",
    help: "Esta faixa ajuda a classificar o potencial, sem estimar crédito financeiro exato.",
    type: "single",
    category: "calculo",
    condition: "tic_track",
    options: [
      choice("ate_500k", "Até R$ 500 mil", "Operação inicial", "500k"),
      choice("de_500k_5m", "R$ 500 mil a R$ 5 milhões", "Operação em crescimento", "5M", "orange"),
      choice("de_5m_50m", "R$ 5 milhões a R$ 50 milhões", "Operação relevante", "50M", "yellow"),
      choice("acima_50m", "Acima de R$ 50 milhões", "Operação de grande porte", "50M+", "orange"),
      choice("nao_sei", "Não sei", "Classificaremos como potencial a validar", "?"),
    ],
  },
  {
    id: "finalidade_renuncia_tecnologia",
    order: 24,
    stage: 5,
    section: "TRILHA: RENÚNCIA FISCAL EM TECNOLOGIA",
    title: "Qual finalidade faz mais sentido para uma operação de Renúncia Fiscal em Tecnologia?",
    help: "A finalidade define a rota legal e o limite aplicável. Não é preciso ter uma estrutura pronta agora.",
    type: "single",
    category: "corte",
    condition: "renuncia_track",
    options: [
      choice("educacao_pesquisa", "Educação, capacitação ou pesquisa em tecnologia", "Rota com teto de 1,5% do lucro operacional", "1,5%", "yellow"),
      choice("trabalhador_comunidade", "Benefício para trabalhadores, dependentes ou comunidade", "Rota com teto de 2% do lucro operacional", "2%", "orange"),
      choice("nao_sei", "Ainda estou definindo", "Vamos avaliar a estrutura sem fixar uma rota agora", "?"),
      choice("nao_avaliar", "Não faz sentido avaliar agora", "Não abriremos perguntas operacionais desta trilha", "—"),
    ],
  },
  {
    id: "lucro_operacional_faixa",
    order: 25,
    stage: 5,
    section: "TRILHA: RENÚNCIA FISCAL EM TECNOLOGIA",
    title: "Qual foi o lucro operacional aproximado da empresa no último ano?",
    help: "Esta faixa define o teto legal da simulação. Se não souber, o diagnóstico mantém a trilha sem estimativa financeira.",
    type: "single",
    category: "calculo",
    condition: "renuncia_operational_track",
    options: [
      choice("ate_1m", "Até R$ 1 milhão", "Lucro operacional de menor porte", "1M"),
      choice("de_1m_10m", "R$ 1 milhão a R$ 10 milhões", "Faixa intermediária", "10M", "orange"),
      choice("de_10m_50m", "R$ 10 milhões a R$ 50 milhões", "Faixa relevante", "50M", "yellow"),
      choice("de_50m_200m", "R$ 50 milhões a R$ 200 milhões", "Faixa de grande porte", "200M", "orange"),
      choice("acima_200m", "Acima de R$ 200 milhões", "Faixa de grande porte", "200M+", "yellow"),
      choice("nao_sei", "Não sei", "Mostraremos a aderência sem calcular o teto", "?"),
    ],
  },
  {
    id: "modelo_execucao_tecnologia",
    order: 26,
    stage: 5,
    section: "TRILHA: RENÚNCIA FISCAL EM TECNOLOGIA",
    title: "Como a empresa executa tecnologia hoje?",
    help: "Marque todas as formas relevantes. A composição da operação ajuda a avaliar a aderência da estrutura.",
    type: "multiple",
    category: "priorizacao",
    condition: "renuncia_operational_track",
    exclusiveValues: ["sem_operacao", "nao_sei"],
    options: [
      choice("equipe_clt", "Equipe interna contratada", "Profissionais de tecnologia no quadro da empresa", "CLT", "yellow"),
      choice("profissionais_pj", "Profissionais PJ recorrentes", "Profissionais contratados como pessoa jurídica", "PJ", "orange"),
      choice("consultoria_desenvolvimento", "Consultoria, fábrica de software ou desenvolvimento terceirizado", "Fornecedores que constroem ou evoluem tecnologia", "DEV", "yellow"),
      choice("servicos_gerenciados", "Sustentação ou serviços gerenciados terceirizados", "Operação, infraestrutura ou suporte contratado", "OPS", "orange"),
      choice("sem_operacao", "Não temos operação de tecnologia relevante", "A trilha perde aderência neste momento", "—"),
      choice("nao_sei", "Não sei", "Vamos manter a leitura como potencial a estruturar", "?"),
    ],
  },
  {
    id: "gasto_tecnologia_renuncia",
    order: 27,
    stage: 5,
    section: "TRILHA: RENÚNCIA FISCAL EM TECNOLOGIA",
    title: "Quanto a empresa movimenta por ano em equipe e serviços de tecnologia?",
    help: "Use uma faixa ampla. Este valor mede a escala operacional; a base fiscal final depende da estrutura e do teto legal.",
    type: "single",
    category: "calculo",
    condition: "renuncia_operational_track",
    options: [
      choice("ate_50k", "Até R$ 50 mil", "Operação inicial", "50k"),
      choice("de_50k_200k", "R$ 50 mil a R$ 200 mil", "Operação recorrente", "200k", "orange"),
      choice("de_200k_1m", "R$ 200 mil a R$ 1 milhão", "Operação estruturada", "1M", "yellow"),
      choice("de_1m_5m", "R$ 1 milhão a R$ 5 milhões", "Operação relevante", "5M", "orange"),
      choice("acima_5m", "Acima de R$ 5 milhões", "Operação de grande porte", "5M+", "yellow"),
      choice("nao_sei", "Não sei", "Mostraremos a aderência sem estimativa financeira", "?"),
    ],
  },
  {
    id: "estagio_projeto",
    order: 28,
    stage: 5,
    section: "TRILHA: FUNDING E FOMENTO",
    title: "Em que fase está o principal projeto de inovação?",
    help: "Essa etapa ajuda a aproximar a empresa dos formatos de apoio mais compatíveis.",
    type: "single",
    category: "priorizacao",
    condition: "funding_track",
    options: [
      choice("ideia", "Ideia inicial", "Ainda em definição", "01"),
      choice("prototipo", "Protótipo ou testes", "Já existe uma solução sendo validada", "02", "orange"),
      choice("escalar", "Validado, pronto para escalar", "A solução está pronta para ganhar escala", "03", "yellow"),
      choice("mercado", "Já está no mercado", "A solução já foi lançada", "04", "orange"),
      choice("nao_sei", "Não sei", "Precisamos entender melhor a maturidade", "?"),
    ],
  },
  {
    id: "aceita_ict_coexecucao",
    order: 29,
    stage: 5,
    section: "TRILHA: FUNDING E FOMENTO",
    title: "A empresa aceitaria desenvolver o projeto junto com universidade, instituto ou laboratório, dividindo custos?",
    help: "Algumas oportunidades de cofinanciamento dependem dessa colaboração técnica.",
    type: "single",
    category: "corte",
    condition: "funding_track",
    options: [
      choice("sim", "Sim", "A colaboração faz sentido", "✓", "yellow"),
      choice("talvez", "Talvez", "Podemos avaliar parceiro e formato", "~", "orange"),
      choice("nao", "Não", "A empresa prefere desenvolver sozinha", "—"),
      choice("nao_sei", "Não sei", "Precisa de uma conversa interna", "?"),
    ],
  },
  {
    id: "apetite_divida",
    order: 30,
    stage: 5,
    section: "TRILHA: FUNDING E FOMENTO",
    title: "A empresa aceitaria financiamento com juros menores que os de mercado?",
    help: "O crédito não reembolsável é diferente de financiamento. Queremos entender o apetite para cada caminho.",
    type: "single",
    category: "corte",
    condition: "funding_track",
    options: [
      choice("sim", "Sim", "Financiamento pode fazer sentido", "✓", "yellow"),
      choice("talvez", "Talvez", "Depende das condições", "~", "orange"),
      choice("nao", "Não", "A empresa não busca dívida agora", "—"),
    ],
  },
  {
    id: "capacidade_credito",
    order: 31,
    stage: 5,
    section: "TRILHA: FUNDING E FOMENTO",
    title: "A empresa tem capacidade de dar garantias ou comprovar capacidade de pagamento?",
    help: "Essa resposta ajuda a indicar a maturidade para linhas de financiamento.",
    type: "single",
    category: "risco",
    condition: "funding_track",
    options: [
      choice("sim", "Sim", "Há capacidade aparente", "✓", "yellow"),
      choice("talvez", "Talvez", "Precisamos estruturar melhor", "~", "orange"),
      choice("nao", "Não", "Há uma limitação importante", "—", "orange"),
      choice("nao_sei", "Não sei", "Precisamos validar com financeiro", "?"),
    ],
  },
  {
    id: "apetite_equity",
    order: 32,
    stage: 5,
    section: "TRILHA: FUNDING E FOMENTO",
    title: "A empresa aceitaria trazer investidor externo em troca de participação no negócio?",
    help: "Isso ajuda a priorizar caminhos ligados a investimento e estruturação de startup.",
    type: "single",
    category: "priorizacao",
    condition: "funding_track",
    options: [
      choice("sim", "Sim", "A empresa considera equity", "✓", "yellow"),
      choice("talvez", "Talvez", "Pode avaliar uma proposta adequada", "~", "orange"),
      choice("nao", "Não", "A empresa não busca investidor agora", "—"),
    ],
  },
  {
    id: "atua_semicondutores",
    order: 33,
    stage: 5,
    section: "OPORTUNIDADE SETORIAL",
    title: "A empresa atua com desenvolvimento, projeto ou fabricação de semicondutores ou displays?",
    help: "A resposta indica uma oportunidade setorial que exige análise específica.",
    type: "single",
    category: "corte",
    condition: "semiconductor_track",
    options: [
      choice("sim", "Sim", "Há atuação direta na cadeia", "✓", "yellow"),
      choice("nao", "Não", "Não há atuação direta", "—"),
      choice("nao_sei", "Não sei", "Precisamos validar a cadeia de atuação", "?"),
    ],
  },
  {
    id: "atua_rota2030",
    order: 34,
    stage: 5,
    section: "OPORTUNIDADE SETORIAL",
    title: "A empresa atua na cadeia automotiva ou de mobilidade com desenvolvimento tecnológico?",
    help: "A resposta indica uma oportunidade setorial que exige análise específica.",
    type: "single",
    category: "corte",
    condition: "automotive_track",
    options: [
      choice("sim", "Sim", "Há atuação direta na cadeia", "✓", "yellow"),
      choice("nao", "Não", "Não há atuação direta", "—"),
      choice("nao_sei", "Não sei", "Precisamos validar a cadeia de atuação", "?"),
    ],
  },
]);

export const QUESTION_INDEX = Object.freeze(
  Object.fromEntries(QUESTION_BANK.map((question) => [question.id, question])),
);

export const OBJECTIVE_PRIORITIES = Object.freeze({
  reduzir_impostos: ["LEIBEM", "RENUCIA_TECNOLOGIA", "LEIBEM_ICT_19A", "LEITIC"],
  buscar_funding: ["FOMENTO_NAOREEMB", "EMBRAPII", "CREDITO_SUBSIDIADO", "STARTUPLC182"],
  financiar_expansao: ["CREDITO_SUBSIDIADO", "LEIBEM", "RENUCIA_TECNOLOGIA", "LEITIC"],
  atrair_investidor: ["STARTUPLC182", "FOMENTO_NAOREEMB"],
  apoiar_projetos: ["RENUCIA_TECNOLOGIA", "LEIBEM_ICT_19A"],
  nao_sei: [],
});

export const MECHANISM_META = Object.freeze({
  LEIBEM: { name: "Lei do Bem", source: LEGAL_SOURCES.LEIBEM },
  LEIBEM_ICT_19A: { name: "Projeto com ICT", source: LEGAL_SOURCES.LEIBEM_ICT_19A },
  LEITIC: { name: "Lei de TICs", source: LEGAL_SOURCES.LEITIC },
  RENUCIA_TECNOLOGIA: { name: "Renúncia Fiscal em Tecnologia", source: LEGAL_SOURCES.RENUCIA_TECNOLOGIA },
  FOMENTO_NAOREEMB: { name: "Fomento não reembolsável", source: null },
  CREDITO_SUBSIDIADO: { name: "Crédito subsidiado", source: null },
  EMBRAPII: { name: "Cofinanciamento EMBRAPII", source: null },
  STARTUPLC182: { name: "Marco Legal das Startups", source: LEGAL_SOURCES.STARTUPLC182 },
  PADIS: { name: "PADIS", source: null },
  ROTA2030: { name: "Rota 2030", source: null },
});
