/* Generated by build-bundle.mjs. Do not edit directly. */

const APP_META = Object.freeze({
  name: "Diagnóstico de Incentivos e Funding",
  brand: "MonyU",
  rulesVersion: "1.0.2",
  rulesUpdatedAt: "2026-07-10",
  storageKey: "monyu-diagnostico-v2",
});

const STATUS = Object.freeze({
  AVAILABLE: "APROVEITAVEL_AGORA",
  VALIDATE: "POTENCIAL_VALIDAR",
  PREPARE: "PREPARAR",
  OPTIMIZE: "JA_USA_OTIMIZAR",
  NOT_RELEVANT: "NAO_RELEVANTE",
  BLOCKED: "BLOQUEADO",
});

const STATUS_COPY = Object.freeze({
  [STATUS.AVAILABLE]: { label: "Pode aproveitar agora", tone: "positive" },
  [STATUS.VALIDATE]: { label: "Tem potencial, mas precisa validar", tone: "attention" },
  [STATUS.PREPARE]: { label: "Pode se preparar para acessar", tone: "neutral" },
  [STATUS.OPTIMIZE]: { label: "Pode otimizar o uso", tone: "positive" },
  [STATUS.NOT_RELEVANT]: { label: "Não é indicado agora", tone: "muted" },
  [STATUS.BLOCKED]: { label: "Há um impeditivo agora", tone: "danger" },
});

const STEPS = Object.freeze([
  { id: 1, name: "Direcionamento" },
  { id: 2, name: "Estrutura da empresa" },
  { id: 3, name: "Perfil de inovação" },
  { id: 4, name: "Capacidade e evidências" },
  { id: 5, name: "Trilhas relevantes" },
  { id: 6, name: "Resultado" },
]);

const LEGAL_SOURCES = Object.freeze({
  LEIBEM: {
    label: "Lei nº 11.196/2005 e Decreto nº 5.798/2006",
    url: "https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2005/lei/L11196compilado.htm",
  },
  LEIBEM_ICT_19A: {
    label: "Lei nº 11.196/2005, art. 19-A",
    url: "https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2005/lei/L11196compilado.htm",
  },
  LEITIC: {
    label: "Lei nº 8.248/1991 e legislação correlata",
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8248.htm",
  },
  RENUCIA_TECNOLOGIA: {
    label: "Lei nº 9.249/1995, art. 13, § 2º, II e III, e IN SRF nº 87/1996",
    url: "https://www.planalto.gov.br/ccivil_03/leis/l9249.htm",
  },
  STARTUPLC182: {
    label: "Lei Complementar nº 182/2021",
    url: "https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp182.htm",
  },
});

const PARAMETERS = Object.freeze({
  effectiveFrom: "2026-07-10",
  source: "Textos legais oficiais indicados em LEGAL_SOURCES; revisão profissional recomendada antes de uso fiscal.",
  taxRate: 0.34,
  leiBem: {
    baseExclusion: 0.6,
    researcherIncreaseHigh: 0.2,
    intellectualPropertyIncrease: 0.2,
    maxExclusion: 1,
  },
  leiBemIct19A: {
    conservativeExclusion: 0.5,
  },
  renunciaTecnologia: {
    educationResearchOperatingProfitLimit: 0.015,
    workerCommunityOperatingProfitLimit: 0.02,
    irpjRate: 0.15,
    irpjAdditionalRate: 0.1,
    irpjAdditionalAnnualThreshold: 240000,
    csllRate: 0.09,
  },
  embrapii: {
    cofundingMin: null,
    cofundingMax: null,
  },
  ranges: {
    innovationSpend: {
      ate_50k: { min: 0, max: 50000, label: "Até R$ 50 mil" },
      de_50k_200k: { min: 50000, max: 200000, label: "R$ 50 mil a R$ 200 mil" },
      de_200k_1m: { min: 200000, max: 1000000, label: "R$ 200 mil a R$ 1 mi" },
      de_1m_5m: { min: 1000000, max: 5000000, label: "R$ 1 mi a R$ 5 mi" },
      acima_5m: { min: 5000000, max: null, label: "Acima de R$ 5 mi" },
    },
    ictProject: {
      ate_50k: { min: 0, max: 50000, label: "Até R$ 50 mil" },
      de_50k_200k: { min: 50000, max: 200000, label: "R$ 50 mil a R$ 200 mil" },
      de_200k_1m: { min: 200000, max: 1000000, label: "R$ 200 mil a R$ 1 mi" },
      de_1m_5m: { min: 1000000, max: 5000000, label: "R$ 1 mi a R$ 5 mi" },
      acima_5m: { min: 5000000, max: null, label: "Acima de R$ 5 mi" },
    },
    technologyOperation: {
      ate_50k: { min: 0, max: 50000, label: "Até R$ 50 mil" },
      de_50k_200k: { min: 50000, max: 200000, label: "R$ 50 mil a R$ 200 mil" },
      de_200k_1m: { min: 200000, max: 1000000, label: "R$ 200 mil a R$ 1 mi" },
      de_1m_5m: { min: 1000000, max: 5000000, label: "R$ 1 mi a R$ 5 mi" },
      acima_5m: { min: 5000000, max: null, label: "Acima de R$ 5 mi" },
    },
    operatingProfit: {
      ate_1m: { min: 0, max: 1000000, label: "Até R$ 1 milhão" },
      de_1m_10m: { min: 1000000, max: 10000000, label: "R$ 1 milhão a R$ 10 milhões" },
      de_10m_50m: { min: 10000000, max: 50000000, label: "R$ 10 milhões a R$ 50 milhões" },
      de_50m_200m: { min: 50000000, max: 200000000, label: "R$ 50 milhões a R$ 200 milhões" },
      acima_200m: { min: 200000000, max: null, label: "Acima de R$ 200 milhões" },
    },
    ticRevenue: {
      ate_500k: { min: 0, max: 500000, label: "Até R$ 500 mil" },
      de_500k_5m: { min: 500000, max: 5000000, label: "R$ 500 mil a R$ 5 mi" },
      de_5m_50m: { min: 5000000, max: 50000000, label: "R$ 5 mi a R$ 50 mi" },
      acima_50m: { min: 50000000, max: null, label: "Acima de R$ 50 mi" },
    },
  },
});

const choice = (value, label, detail, symbol, tone = "pink") => ({
  value,
  label,
  detail,
  symbol,
  tone,
});

const QUESTION_BANK = Object.freeze([
  {
    id: "objetivo_principal",
    order: 1,
    stage: 1,
    section: "COMEÇAMOS PELO ESSENCIAL",
    title: "O que a empresa mais quer resolver agora?",
    help: "Escolha a prioridade que melhor representa este momento.",
    type: "single",
    category: "priorizacao",
    condition: "always",
    options: [
      choice("reduzir_impostos", "Reduzir impostos", "Encontrar incentivos fiscais aplicáveis", "R$"),
      choice("buscar_funding", "Buscar dinheiro para inovar ou crescer", "Mapear fomento e recursos não reembolsáveis", "+", "orange"),
      choice("financiar_expansao", "Financiar máquinas, equipamentos ou expansão", "Avaliar crédito e linhas de financiamento", "↗", "yellow"),
      choice("atrair_investidor", "Atrair investidor", "Entender caminhos de estruturação e capital", "◆", "orange"),
      choice("apoiar_projetos", "Apoiar educação, pesquisa ou impacto social", "Avaliar Renúncia Fiscal em Tecnologia", "◌", "yellow"),
      choice("nao_sei", "Ainda não sei", "Vamos identificar as oportunidades com você", "?"),
    ],
  },
  {
    id: "regime_tributario",
    order: 2,
    stage: 2,
    section: "ESTRUTURA DA EMPRESA",
    title: "Como a empresa paga seus impostos hoje?",
    help: "Esta resposta define quais incentivos podem ser aproveitados agora.",
    type: "single",
    category: "corte",
    condition: "always",
    options: [
      choice("simples_nacional", "Simples Nacional", "Regime simplificado para pequenos negócios", "S"),
      choice("lucro_presumido", "Lucro Presumido", "Tributação baseada em uma margem presumida", "LP", "orange"),
      choice("lucro_real", "Lucro Real", "Tributação baseada no lucro efetivamente apurado", "LR", "yellow"),
      choice("nao_sei", "Não sei", "Continuaremos com uma estimativa orientada", "?"),
    ],
  },
  {
    id: "faturamento_faixa",
    order: 3,
    stage: 2,
    section: "ESTRUTURA DA EMPRESA",
    title: "Qual é o faturamento anual aproximado da empresa?",
    help: "Uma faixa é suficiente. Não pedimos números exatos nesta etapa.",
    type: "single",
    category: "corte",
    condition: "always",
    options: [
      choice("ate_360k", "Até R$ 360 mil", "Faixa de microempresa", "360k"),
      choice("de_360k_48m", "R$ 360 mil a R$ 4,8 milhões", "Faixa de pequena empresa", "4,8M", "orange"),
      choice("de_48m_16m", "R$ 4,8 milhões a R$ 16 milhões", "Faixa relevante para startups", "16M", "yellow"),
      choice("de_16m_300m", "R$ 16 milhões a R$ 300 milhões", "Empresa em escala", "300M", "orange"),
      choice("acima_300m", "Acima de R$ 300 milhões", "Grande empresa", "300+", "yellow"),
      choice("nao_sei", "Não sei", "Seguimos com a melhor estimativa possível", "?"),
    ],
  },
  {
    id: "tempo_existencia",
    order: 4,
    stage: 2,
    section: "ESTRUTURA DA EMPRESA",
    title: "Há quanto tempo a empresa existe?",
    help: "Isso ajuda a identificar caminhos voltados a negócios inovadores em formação.",
    type: "single",
    category: "corte",
    condition: "always",
    options: [
      choice("menos_2", "Menos de 2 anos", "Negócio em fase inicial", "2"),
      choice("de_2_5", "De 2 a 5 anos", "Negócio em consolidação", "5", "orange"),
      choice("de_5_10", "De 5 a 10 anos", "Negócio em expansão", "10", "yellow"),
      choice("mais_10", "Mais de 10 anos", "Empresa madura", "10+", "orange"),
      choice("nao_sei", "Não sei", "Seguimos sem usar esse critério", "?"),
    ],
  },
  {
    id: "setor",
    order: 5,
    stage: 2,
    section: "ESTRUTURA DA EMPRESA",
    title: "Qual é o principal setor da empresa?",
    help: "Escolha o setor que mais representa a operação e a receita atual.",
    type: "single",
    category: "corte",
    condition: "always",
    options: [
      choice("tecnologia_software", "Tecnologia ou software", "Produtos, plataformas ou serviços digitais", "<>"),
      choice("eletronicos_hardware", "Eletrônicos ou hardware", "Equipamentos, componentes e dispositivos", "HW", "orange"),
      choice("industria", "Indústria geral", "Transformação ou produção", "IN", "yellow"),
      choice("servicos", "Serviços", "Operações e atendimento especializado", "SV", "orange"),
      choice("saude", "Saúde", "Serviços, produtos ou tecnologia em saúde", "+", "yellow"),
      choice("agro", "Agro", "Produção, insumos ou agrotecnologia", "AG", "orange"),
      choice("financeiro", "Financeiro", "Serviços financeiros, seguros ou fintech", "R$", "yellow"),
      choice("varejo", "Varejo ou comércio", "Comércio físico ou digital", "VC", "orange"),
      choice("semicondutores", "Semicondutores", "Chips, displays ou cadeia associada", "SC", "yellow"),
      choice("automotivo_mobilidade", "Automotivo ou mobilidade", "Veículos, autopeças ou mobilidade", "MV", "orange"),
      choice("outro", "Outro", "Setor não listado", "…"),
    ],
  },
  {
    id: "regularidade_fiscal",
    order: 6,
    stage: 2,
    section: "ESTRUTURA DA EMPRESA",
    title: "A empresa está em dia com os impostos federais ou consegue regularizar rapidamente?",
    help: "A regularidade costuma ser exigida para benefícios e linhas de financiamento.",
    type: "single",
    category: "risco",
    condition: "always",
    options: [
      choice("sim", "Sim", "A situação está regular", "✓", "yellow"),
      choice("nao", "Não", "Há pendências relevantes", "!", "orange"),
      choice("nao_sei", "Não sei", "Precisamos confirmar", "?"),
      choice("parcelamento_em_dia", "Existe parcelamento em dia", "A situação pode ser comprovada", "≡", "yellow"),
    ],
  },
  {
    id: "atividades_inovacao",
    order: 7,
    stage: 3,
    section: "PERFIL DE INOVAÇÃO",
    title: "A empresa faz alguma destas atividades?",
    help: "Marque todas as que se aplicam. Não é preciso usar linguagem técnica.",
    type: "multiple",
    category: "corte",
    condition: "always",
    exclusiveValues: ["nenhuma", "nao_sei"],
    options: [
      choice("produto_fisico", "Cria produto físico", "Produtos, equipamentos ou componentes próprios", "PF", "yellow"),
      choice("software_proprio", "Desenvolve software, sistema ou plataforma própria", "Soluções digitais que a empresa cria ou evolui", "<>"),
      choice("melhoria_processo", "Melhora processo, fórmula, método ou operação", "Testes para fazer melhor, mais rápido ou com menos custo", "↗", "orange"),
      choice("testes_prototipos", "Faz testes, protótipos ou experimentos", "Validação técnica antes de escalar", "⌁", "yellow"),
      choice("parceria_ict", "Trabalha com universidade, instituto ou laboratório", "Desenvolvimento com parceiro técnico", "UT", "orange"),
      choice("nenhuma", "Nenhuma dessas", "Não identifico atividades desse tipo agora", "—"),
      choice("nao_sei", "Não sei", "Quero ajuda para reconhecer essas atividades", "?"),
    ],
  },
  {
    id: "inovacao_informal",
    order: 8,
    stage: 3,
    section: "UM OLHAR MAIS PRÓXIMO",
    title: "Mesmo informalmente, a empresa testa novas formas de produzir, vender, atender ou reduzir custos?",
    help: "Muitas empresas inovam sem chamar isso de inovação. Esta pergunta evita descartar uma oportunidade cedo demais.",
    type: "single",
    category: "corte",
    condition: "needs_informal_check",
    options: [
      choice("com_frequencia", "Sim, com frequência", "Esse tipo de melhoria faz parte da rotina", "✓", "yellow"),
      choice("as_vezes", "Às vezes", "Acontece em iniciativas específicas", "~", "orange"),
      choice("nao", "Não", "Não identifico isso agora", "—"),
      choice("nao_sei", "Não sei", "Precisamos conversar melhor sobre o dia a dia", "?"),
    ],
  },
  {
    id: "lucro_ou_imposto",
    order: 9,
    stage: 4,
    section: "CAPACIDADE FISCAL",
    title: "No último ano, a empresa teve lucro tributável ou imposto relevante a pagar?",
    help: "É uma referência para saber se um benefício fiscal pode gerar efeito imediato.",
    type: "single",
    category: "calculo",
    condition: "innovation_positive",
    options: [
      choice("sim", "Sim", "Há lucro ou imposto relevante a pagar", "✓", "yellow"),
      choice("prejuizo", "Não, teve prejuízo", "O benefício pode não virar economia agora", "—", "orange"),
      choice("nao_sei", "Não sei", "Precisamos confirmar com a contabilidade", "?"),
      choice("validar_contador", "Prefiro validar com o contador", "Seguiremos com uma estimativa prudente", "CT", "orange"),
    ],
  },
  {
    id: "gasto_inovacao",
    order: 10,
    stage: 4,
    section: "CAPACIDADE FISCAL",
    title: "Quanto a empresa gasta por ano com criação, melhoria, desenvolvimento, testes ou projetos técnicos?",
    help: "Considere pessoas, materiais, testes e outros gastos ligados aos projetos. Uma faixa basta.",
    type: "single",
    category: "calculo",
    condition: "innovation_positive",
    options: [
      choice("ate_50k", "Até R$ 50 mil", "Investimento inicial", "50k"),
      choice("de_50k_200k", "R$ 50 mil a R$ 200 mil", "Investimento recorrente", "200k", "orange"),
      choice("de_200k_1m", "R$ 200 mil a R$ 1 milhão", "Investimento relevante", "1M", "yellow"),
      choice("de_1m_5m", "R$ 1 milhão a R$ 5 milhões", "Investimento estruturado", "5M", "orange"),
      choice("acima_5m", "Acima de R$ 5 milhões", "Investimento de grande porte", "5M+", "yellow"),
      choice("nao_sei", "Não sei", "Mostraremos oportunidades sem cálculo financeiro", "?"),
    ],
  },
  {
    id: "maturidade_contabil",
    order: 11,
    stage: 4,
    section: "CAPACIDADE FISCAL",
    title: "A empresa consegue separar esses gastos por projeto ou iniciativa?",
    help: "Não precisa estar perfeito. Queremos entender o nível atual de organização.",
    type: "single",
    category: "risco",
    condition: "innovation_positive",
    options: [
      choice("com_clareza", "Sim, com clareza", "Gastos organizados por projeto ou centro de custo", "✓", "yellow"),
      choice("mais_ou_menos", "Mais ou menos", "Parte dos gastos está identificada", "~", "orange"),
      choice("nao", "Não", "Os gastos estão misturados na operação", "—", "orange"),
      choice("nao_sei", "Não sei", "Precisamos validar com a equipe financeira", "?"),
    ],
  },
  {
    id: "maturidade_documental",
    order: 12,
    stage: 4,
    section: "CAPACIDADE FISCAL",
    title: "A empresa guarda evidências dos projetos, como relatórios, testes, protótipos, atas ou registros?",
    help: "Esses materiais ajudam a demonstrar o que foi desenvolvido e como o dinheiro foi usado.",
    type: "single",
    category: "risco",
    condition: "innovation_positive",
    options: [
      choice("bem_organizado", "Sim, bem organizado", "Documentação disponível e acessível", "✓", "yellow"),
      choice("algumas_evidencias", "Temos algumas evidências", "Há material, mas precisa ser reunido", "~", "orange"),
      choice("quase_nada", "Quase nada", "Ainda não há uma rotina de registro", "—", "orange"),
      choice("nao_sei", "Não sei", "Precisamos confirmar com quem toca os projetos", "?"),
    ],
  },
  {
    id: "uso_leibem",
    order: 13,
    stage: 5,
    section: "TRILHA: LEI DO BEM",
    title: "A empresa já aproveita a Lei do Bem hoje?",
    help: "A Lei do Bem pode reduzir impostos ligados a gastos com desenvolvimento e melhoria tecnológica.",
    type: "single",
    category: "corte",
    condition: "leibem_track",
    options: [
      choice("usa_hoje", "Sim, uso hoje", "Vamos buscar oportunidades de otimização", "✓", "yellow"),
      choice("ja_usei", "Já usei, mas parei", "Vamos entender se é possível retomar", "↺", "orange"),
      choice("nunca_usei", "Nunca usei", "Avaliaremos o potencial atual", "+"),
      choice("nao_sei", "Não sei", "Seguiremos com uma análise prudente", "?"),
    ],
  },
  {
    id: "pesquisadores_equipe",
    order: 14,
    stage: 5,
    section: "TRILHA: LEI DO BEM",
    title: "A empresa tem pessoas contratadas dedicadas a essas atividades de criação ou melhoria?",
    help: "O aumento de pesquisadores pode ampliar o potencial de benefício em alguns casos.",
    type: "single",
    category: "calculo",
    condition: "leibem_track",
    options: [
      choice("nao", "Não", "As atividades não têm uma equipe dedicada", "—"),
      choice("sim_sem_aumento", "Sim, mas sem aumento recente", "Há equipe, mas sem expansão neste ano", "↔", "orange"),
      choice("sim_com_aumento", "Sim, e aumentou a equipe neste ano", "Há crescimento da equipe dedicada", "↑", "yellow"),
      choice("nao_sei", "Não sei", "Precisamos confirmar com RH ou liderança técnica", "?"),
    ],
  },
  {
    id: "propriedade_intelectual",
    order: 15,
    stage: 5,
    section: "TRILHA: LEI DO BEM",
    title: "Algum projeto gerou patente concedida ou cultivar registrado?",
    help: "Algumas situações de propriedade intelectual podem influenciar a estimativa, conforme a lei.",
    type: "single",
    category: "calculo",
    condition: "leibem_track",
    options: [
      choice("patente_concedida", "Sim, patente concedida", "Há patente vinculada a um projeto", "P", "yellow"),
      choice("cultivar_registrado", "Sim, cultivar registrado", "Há registro de cultivar", "C", "yellow"),
      choice("pedido_andamento", "Pedido em andamento", "Ainda sem concessão", "…", "orange"),
      choice("software_registrado", "Apenas software registrado", "Registro de software não aciona esse adicional", "<>"),
      choice("nao", "Não", "Não há patente ou cultivar aplicável", "—"),
      choice("nao_sei", "Não sei", "Precisamos confirmar", "?"),
    ],
  },
  {
    id: "compra_equipamentos",
    order: 16,
    stage: 5,
    section: "TRILHA: LEI DO BEM",
    title: "A empresa comprou máquinas, equipamentos ou instrumentos para usar nesses projetos?",
    help: "Essa informação orienta uma conversa mais precisa sobre os itens que podem ser analisados.",
    type: "single",
    category: "calculo",
    condition: "leibem_track",
    options: [
      choice("sim", "Sim", "Há aquisição ligada a projetos", "✓", "yellow"),
      choice("nao", "Não", "Não houve aquisição relevante", "—"),
      choice("nao_sei", "Não sei", "Precisamos confirmar", "?"),
    ],
  },
  {
    id: "projeto_ict",
    order: 17,
    stage: 5,
    section: "TRILHA: LEI DO BEM",
    title: "A empresa tem projeto formal pago com universidade, instituto de pesquisa ou laboratório?",
    help: "Essa parceria pode abrir uma trilha específica, desde que o projeto esteja corretamente estruturado.",
    type: "single",
    category: "corte",
    condition: "leibem_track",
    options: [
      choice("sim", "Sim", "Existe projeto formal contratado", "✓", "yellow"),
      choice("nao", "Não", "Não há projeto formal desse tipo", "—"),
      choice("negociando", "Estamos negociando", "A parceria está sendo estruturada", "~", "orange"),
      choice("nao_sei", "Não sei", "Precisamos confirmar com a área técnica", "?"),
    ],
  },
  {
    id: "ict_19a_aprovacao",
    order: 18,
    stage: 5,
    section: "TRILHA: PROJETO COM ICT",
    title: "Esse projeto com universidade ou instituto tem aprovação formal ou portaria para uso do incentivo?",
    help: "A aprovação formal é decisiva para transformar esta possibilidade em benefício aplicável.",
    type: "single",
    category: "risco",
    condition: "ict_19a_track",
    options: [
      choice("sim", "Sim", "A aprovação ou portaria está disponível", "✓", "yellow"),
      choice("nao", "Não", "O projeto não tem aprovação formal", "—", "orange"),
      choice("nao_sei", "Não sei", "Precisamos confirmar a documentação", "?"),
      choice("a_estruturar", "Ainda será estruturado", "A parceria está em fase inicial", "~", "orange"),
    ],
  },
  {
    id: "valor_projeto_ict",
    order: 19,
    stage: 5,
    section: "TRILHA: PROJETO COM ICT",
    title: "Qual é o valor aproximado que a empresa paga ou pretende pagar nesse projeto?",
    help: "Use uma faixa aproximada. Ela serve somente para a estimativa preliminar.",
    type: "single",
    category: "calculo",
    condition: "ict_19a_track",
    options: [
      choice("ate_50k", "Até R$ 50 mil", "Projeto inicial", "50k"),
      choice("de_50k_200k", "R$ 50 mil a R$ 200 mil", "Projeto em estruturação", "200k", "orange"),
      choice("de_200k_1m", "R$ 200 mil a R$ 1 milhão", "Projeto relevante", "1M", "yellow"),
      choice("de_1m_5m", "R$ 1 milhão a R$ 5 milhões", "Projeto robusto", "5M", "orange"),
      choice("acima_5m", "Acima de R$ 5 milhões", "Projeto de grande porte", "5M+", "yellow"),
      choice("nao_sei", "Não sei", "Mostraremos a trilha sem cálculo", "?"),
    ],
  },
  {
    id: "atividade_tic_brasil",
    order: 20,
    stage: 5,
    section: "TRILHA: LEI DE TICS",
    title: "A empresa desenvolve ou produz, no Brasil, bens, equipamentos, componentes, hardware, dispositivos conectados ou soluções de tecnologia?",
    help: "Revender produto de terceiros, por si só, não costuma abrir esta trilha.",
    type: "single",
    category: "corte",
    condition: "tic_track",
    options: [
      choice("sim", "Sim", "Há desenvolvimento ou produção no Brasil", "✓", "yellow"),
      choice("nao", "Não", "Não há desenvolvimento ou produção aplicável", "—"),
      choice("revenda", "Apenas revende produtos de terceiros", "Atividade de revenda isolada", "↔", "orange"),
      choice("nao_sei", "Não sei", "Precisamos analisar o produto e a operação", "?"),
    ],
  },
  {
    id: "ncm_ppb",
    order: 21,
    stage: 5,
    section: "TRILHA: LEI DE TICS",
    title: "A empresa conhece o NCM, enquadramento ou processo produtivo do produto tecnológico?",
    help: "Essas informações são importantes para confirmar o enquadramento da Lei de TICs.",
    type: "single",
    category: "risco",
    condition: "tic_track",
    options: [
      choice("ncm_e_ppb", "Sim, temos NCM e PPB mapeados", "Documentação técnica já identificada", "✓", "yellow"),
      choice("somente_ncm", "Temos NCM, mas não PPB", "Parte do mapeamento já existe", "NCM", "orange"),
      choice("nao", "Não", "Ainda não há enquadramento mapeado", "—", "orange"),
      choice("nao_sei", "Não sei", "Precisamos levantar essas informações", "?"),
    ],
  },
  {
    id: "uso_leitic",
    order: 22,
    stage: 5,
    section: "TRILHA: LEI DE TICS",
    title: "A empresa já é habilitada na Lei de Informática ou Lei de TICs?",
    help: "A habilitação atual muda o foco de enquadramento para otimização.",
    type: "single",
    category: "corte",
    condition: "tic_track",
    options: [
      choice("usa_hoje", "Sim, usa hoje", "Vamos procurar melhorias no uso", "✓", "yellow"),
      choice("ja_foi_habilitada", "Já foi habilitada, mas não usa", "Pode haver caminho de retomada", "↺", "orange"),
      choice("nao", "Não", "Avaliaremos a possibilidade de habilitação", "+"),
      choice("nao_sei", "Não sei", "Precisamos confirmar", "?"),
    ],
  },
  {
    id: "faturamento_tic",
    order: 23,
    stage: 5,
    section: "TRILHA: LEI DE TICS",
    title: "Qual é o faturamento anual aproximado com esses produtos ou soluções de tecnologia?",
    help: "Esta faixa ajuda a classificar o potencial, sem estimar crédito financeiro exato.",
    type: "single",
    category: "calculo",
    condition: "tic_track",
    options: [
      choice("ate_500k", "Até R$ 500 mil", "Operação inicial", "500k"),
      choice("de_500k_5m", "R$ 500 mil a R$ 5 milhões", "Operação em crescimento", "5M", "orange"),
      choice("de_5m_50m", "R$ 5 milhões a R$ 50 milhões", "Operação relevante", "50M", "yellow"),
      choice("acima_50m", "Acima de R$ 50 milhões", "Operação de grande porte", "50M+", "orange"),
      choice("nao_sei", "Não sei", "Classificaremos como potencial a validar", "?"),
    ],
  },
  {
    id: "finalidade_renuncia_tecnologia",
    order: 24,
    stage: 5,
    section: "TRILHA: RENÚNCIA FISCAL EM TECNOLOGIA",
    title: "Qual finalidade faz mais sentido para uma operação de Renúncia Fiscal em Tecnologia?",
    help: "A finalidade define a rota legal e o limite aplicável. Não é preciso ter uma estrutura pronta agora.",
    type: "single",
    category: "corte",
    condition: "renuncia_track",
    options: [
      choice("educacao_pesquisa", "Educação, capacitação ou pesquisa em tecnologia", "Rota com teto de 1,5% do lucro operacional", "1,5%", "yellow"),
      choice("trabalhador_comunidade", "Benefício para trabalhadores, dependentes ou comunidade", "Rota com teto de 2% do lucro operacional", "2%", "orange"),
      choice("nao_sei", "Ainda estou definindo", "Vamos avaliar a estrutura sem fixar uma rota agora", "?"),
      choice("nao_avaliar", "Não faz sentido avaliar agora", "Não abriremos perguntas operacionais desta trilha", "—"),
    ],
  },
  {
    id: "lucro_operacional_faixa",
    order: 25,
    stage: 5,
    section: "TRILHA: RENÚNCIA FISCAL EM TECNOLOGIA",
    title: "Qual foi o lucro operacional aproximado da empresa no último ano?",
    help: "Esta faixa define o teto legal da simulação. Se não souber, o diagnóstico mantém a trilha sem estimativa financeira.",
    type: "single",
    category: "calculo",
    condition: "renuncia_operational_track",
    options: [
      choice("ate_1m", "Até R$ 1 milhão", "Lucro operacional de menor porte", "1M"),
      choice("de_1m_10m", "R$ 1 milhão a R$ 10 milhões", "Faixa intermediária", "10M", "orange"),
      choice("de_10m_50m", "R$ 10 milhões a R$ 50 milhões", "Faixa relevante", "50M", "yellow"),
      choice("de_50m_200m", "R$ 50 milhões a R$ 200 milhões", "Faixa de grande porte", "200M", "orange"),
      choice("acima_200m", "Acima de R$ 200 milhões", "Faixa de grande porte", "200M+", "yellow"),
      choice("nao_sei", "Não sei", "Mostraremos a aderência sem calcular o teto", "?"),
    ],
  },
  {
    id: "modelo_execucao_tecnologia",
    order: 26,
    stage: 5,
    section: "TRILHA: RENÚNCIA FISCAL EM TECNOLOGIA",
    title: "Como a empresa executa tecnologia hoje?",
    help: "Marque todas as formas relevantes. A composição da operação ajuda a avaliar a aderência da estrutura.",
    type: "multiple",
    category: "priorizacao",
    condition: "renuncia_operational_track",
    exclusiveValues: ["sem_operacao", "nao_sei"],
    options: [
      choice("equipe_clt", "Equipe interna contratada", "Profissionais de tecnologia no quadro da empresa", "CLT", "yellow"),
      choice("profissionais_pj", "Profissionais PJ recorrentes", "Profissionais contratados como pessoa jurídica", "PJ", "orange"),
      choice("consultoria_desenvolvimento", "Consultoria, fábrica de software ou desenvolvimento terceirizado", "Fornecedores que constroem ou evoluem tecnologia", "DEV", "yellow"),
      choice("servicos_gerenciados", "Sustentação ou serviços gerenciados terceirizados", "Operação, infraestrutura ou suporte contratado", "OPS", "orange"),
      choice("sem_operacao", "Não temos operação de tecnologia relevante", "A trilha perde aderência neste momento", "—"),
      choice("nao_sei", "Não sei", "Vamos manter a leitura como potencial a estruturar", "?"),
    ],
  },
  {
    id: "gasto_tecnologia_renuncia",
    order: 27,
    stage: 5,
    section: "TRILHA: RENÚNCIA FISCAL EM TECNOLOGIA",
    title: "Quanto a empresa movimenta por ano em equipe e serviços de tecnologia?",
    help: "Use uma faixa ampla. Este valor mede a escala operacional; a base fiscal final depende da estrutura e do teto legal.",
    type: "single",
    category: "calculo",
    condition: "renuncia_operational_track",
    options: [
      choice("ate_50k", "Até R$ 50 mil", "Operação inicial", "50k"),
      choice("de_50k_200k", "R$ 50 mil a R$ 200 mil", "Operação recorrente", "200k", "orange"),
      choice("de_200k_1m", "R$ 200 mil a R$ 1 milhão", "Operação estruturada", "1M", "yellow"),
      choice("de_1m_5m", "R$ 1 milhão a R$ 5 milhões", "Operação relevante", "5M", "orange"),
      choice("acima_5m", "Acima de R$ 5 milhões", "Operação de grande porte", "5M+", "yellow"),
      choice("nao_sei", "Não sei", "Mostraremos a aderência sem estimativa financeira", "?"),
    ],
  },
  {
    id: "estagio_projeto",
    order: 28,
    stage: 5,
    section: "TRILHA: FUNDING E FOMENTO",
    title: "Em que fase está o principal projeto de inovação?",
    help: "Essa etapa ajuda a aproximar a empresa dos formatos de apoio mais compatíveis.",
    type: "single",
    category: "priorizacao",
    condition: "funding_track",
    options: [
      choice("ideia", "Ideia inicial", "Ainda em definição", "01"),
      choice("prototipo", "Protótipo ou testes", "Já existe uma solução sendo validada", "02", "orange"),
      choice("escalar", "Validado, pronto para escalar", "A solução está pronta para ganhar escala", "03", "yellow"),
      choice("mercado", "Já está no mercado", "A solução já foi lançada", "04", "orange"),
      choice("nao_sei", "Não sei", "Precisamos entender melhor a maturidade", "?"),
    ],
  },
  {
    id: "aceita_ict_coexecucao",
    order: 29,
    stage: 5,
    section: "TRILHA: FUNDING E FOMENTO",
    title: "A empresa aceitaria desenvolver o projeto junto com universidade, instituto ou laboratório, dividindo custos?",
    help: "Algumas oportunidades de cofinanciamento dependem dessa colaboração técnica.",
    type: "single",
    category: "corte",
    condition: "funding_track",
    options: [
      choice("sim", "Sim", "A colaboração faz sentido", "✓", "yellow"),
      choice("talvez", "Talvez", "Podemos avaliar parceiro e formato", "~", "orange"),
      choice("nao", "Não", "A empresa prefere desenvolver sozinha", "—"),
      choice("nao_sei", "Não sei", "Precisa de uma conversa interna", "?"),
    ],
  },
  {
    id: "apetite_divida",
    order: 30,
    stage: 5,
    section: "TRILHA: FUNDING E FOMENTO",
    title: "A empresa aceitaria financiamento com juros menores que os de mercado?",
    help: "O crédito não reembolsável é diferente de financiamento. Queremos entender o apetite para cada caminho.",
    type: "single",
    category: "corte",
    condition: "funding_track",
    options: [
      choice("sim", "Sim", "Financiamento pode fazer sentido", "✓", "yellow"),
      choice("talvez", "Talvez", "Depende das condições", "~", "orange"),
      choice("nao", "Não", "A empresa não busca dívida agora", "—"),
    ],
  },
  {
    id: "capacidade_credito",
    order: 31,
    stage: 5,
    section: "TRILHA: FUNDING E FOMENTO",
    title: "A empresa tem capacidade de dar garantias ou comprovar capacidade de pagamento?",
    help: "Essa resposta ajuda a indicar a maturidade para linhas de financiamento.",
    type: "single",
    category: "risco",
    condition: "funding_track",
    options: [
      choice("sim", "Sim", "Há capacidade aparente", "✓", "yellow"),
      choice("talvez", "Talvez", "Precisamos estruturar melhor", "~", "orange"),
      choice("nao", "Não", "Há uma limitação importante", "—", "orange"),
      choice("nao_sei", "Não sei", "Precisamos validar com financeiro", "?"),
    ],
  },
  {
    id: "apetite_equity",
    order: 32,
    stage: 5,
    section: "TRILHA: FUNDING E FOMENTO",
    title: "A empresa aceitaria trazer investidor externo em troca de participação no negócio?",
    help: "Isso ajuda a priorizar caminhos ligados a investimento e estruturação de startup.",
    type: "single",
    category: "priorizacao",
    condition: "funding_track",
    options: [
      choice("sim", "Sim", "A empresa considera equity", "✓", "yellow"),
      choice("talvez", "Talvez", "Pode avaliar uma proposta adequada", "~", "orange"),
      choice("nao", "Não", "A empresa não busca investidor agora", "—"),
    ],
  },
  {
    id: "atua_semicondutores",
    order: 33,
    stage: 5,
    section: "OPORTUNIDADE SETORIAL",
    title: "A empresa atua com desenvolvimento, projeto ou fabricação de semicondutores ou displays?",
    help: "A resposta indica uma oportunidade setorial que exige análise específica.",
    type: "single",
    category: "corte",
    condition: "semiconductor_track",
    options: [
      choice("sim", "Sim", "Há atuação direta na cadeia", "✓", "yellow"),
      choice("nao", "Não", "Não há atuação direta", "—"),
      choice("nao_sei", "Não sei", "Precisamos validar a cadeia de atuação", "?"),
    ],
  },
  {
    id: "atua_rota2030",
    order: 34,
    stage: 5,
    section: "OPORTUNIDADE SETORIAL",
    title: "A empresa atua na cadeia automotiva ou de mobilidade com desenvolvimento tecnológico?",
    help: "A resposta indica uma oportunidade setorial que exige análise específica.",
    type: "single",
    category: "corte",
    condition: "automotive_track",
    options: [
      choice("sim", "Sim", "Há atuação direta na cadeia", "✓", "yellow"),
      choice("nao", "Não", "Não há atuação direta", "—"),
      choice("nao_sei", "Não sei", "Precisamos validar a cadeia de atuação", "?"),
    ],
  },
]);

const QUESTION_INDEX = Object.freeze(
  Object.fromEntries(QUESTION_BANK.map((question) => [question.id, question])),
);

const OBJECTIVE_PRIORITIES = Object.freeze({
  reduzir_impostos: ["LEIBEM", "RENUCIA_TECNOLOGIA", "LEIBEM_ICT_19A", "LEITIC"],
  buscar_funding: ["FOMENTO_NAOREEMB", "EMBRAPII", "CREDITO_SUBSIDIADO", "STARTUPLC182"],
  financiar_expansao: ["CREDITO_SUBSIDIADO", "LEIBEM", "RENUCIA_TECNOLOGIA", "LEITIC"],
  atrair_investidor: ["STARTUPLC182", "FOMENTO_NAOREEMB"],
  apoiar_projetos: ["RENUCIA_TECNOLOGIA", "LEIBEM_ICT_19A"],
  nao_sei: [],
});

const MECHANISM_META = Object.freeze({
  LEIBEM: { name: "Lei do Bem", source: LEGAL_SOURCES.LEIBEM },
  LEIBEM_ICT_19A: { name: "Projeto com ICT", source: LEGAL_SOURCES.LEIBEM_ICT_19A },
  LEITIC: { name: "Lei de TICs", source: LEGAL_SOURCES.LEITIC },
  RENUCIA_TECNOLOGIA: { name: "Renúncia Fiscal em Tecnologia", source: LEGAL_SOURCES.RENUCIA_TECNOLOGIA },
  FOMENTO_NAOREEMB: { name: "Fomento não reembolsável", source: null },
  CREDITO_SUBSIDIADO: { name: "Crédito subsidiado", source: null },
  EMBRAPII: { name: "Cofinanciamento EMBRAPII", source: null },
  STARTUPLC182: { name: "Marco Legal das Startups", source: LEGAL_SOURCES.STARTUPLC182 },
  PADIS: { name: "PADIS", source: null },
  ROTA2030: { name: "Rota 2030", source: null },
});


const FORMAL_INNOVATION = new Set([
  "produto_fisico",
  "software_proprio",
  "melhoria_processo",
  "testes_prototipos",
  "parceria_ict",
]);

const RENUNCIA_OBJECTIVES = new Set([
  "reduzir_impostos",
  "financiar_expansao",
  "apoiar_projetos",
  "nao_sei",
]);
const FUNDING_OBJECTIVES = new Set([
  "buscar_funding",
  "financiar_expansao",
  "atrair_investidor",
  "nao_sei",
]);

const RANGE_BY_ANSWER = Object.freeze({
  gasto_inovacao: "innovationSpend",
  valor_projeto_ict: "ictProject",
  gasto_tecnologia_renuncia: "technologyOperation",
  lucro_operacional_faixa: "operatingProfit",
  faturamento_tic: "ticRevenue",
});

const INSTANT_STATUSES = new Set([STATUS.AVAILABLE, STATUS.OPTIMIZE, STATUS.VALIDATE]);

function list(value) {
  return Array.isArray(value) ? value : [];
}

function hasAny(values, accepted) {
  return values.some((value) => accepted.includes(value));
}

function unique(items) {
  return [...new Set(items.filter(Boolean))];
}

function moneyEstimate(range, exclusionRate, label, premise) {
  if (!range) return null;

  return {
    kind: "financial",
    label,
    min: Math.round(range.min * exclusionRate * PARAMETERS.taxRate),
    max: range.max === null ? null : Math.round(range.max * exclusionRate * PARAMETERS.taxRate),
    premise,
  };
}

function minimumRange(left, right) {
  if (!left || !right) return null;

  return {
    min: Math.min(left.min, right.min),
    max:
      left.max === null
        ? right.max
        : right.max === null
          ? left.max
          : Math.min(left.max, right.max),
  };
}

function taxFromOperationalProfit(value) {
  const config = PARAMETERS.renunciaTecnologia;
  const profit = Math.max(0, value);
  const additionalBase = Math.max(0, profit - config.irpjAdditionalAnnualThreshold);

  return profit * config.irpjRate + additionalBase * config.irpjAdditionalRate + profit * config.csllRate;
}

function renunciaTechnologyEstimate(operatingProfitRange, technologyRange, limitRate, routeLabel) {
  if (!operatingProfitRange || !technologyRange || !limitRate) return null;

  const legalCap = {
    min: operatingProfitRange.min * limitRate,
    max: operatingProfitRange.max === null ? null : operatingProfitRange.max * limitRate,
  };
  const eligibleScale = minimumRange(technologyRange, legalCap);
  const savingsMin =
    taxFromOperationalProfit(operatingProfitRange.min) -
    taxFromOperationalProfit(operatingProfitRange.min - eligibleScale.min);
  const savingsMax =
    operatingProfitRange.max === null || eligibleScale.max === null
      ? null
      : taxFromOperationalProfit(operatingProfitRange.max) -
        taxFromOperationalProfit(operatingProfitRange.max - eligibleScale.max);

  return {
    kind: "financial",
    label: "Economia fiscal preliminar por ano",
    min: Math.round(savingsMin),
    max: savingsMax === null ? null : Math.round(savingsMax),
    premise: `Rota ${routeLabel}; teto de ${(limitRate * 100).toFixed(1)}% sobre o lucro operacional; escala considerada limitada à faixa de tecnologia informada; IRPJ, adicional e CSLL simulados separadamente.`,
  };
}

function qualitativeEstimate(label, detail) {
  return { kind: "qualitative", label, detail };
}

function createMechanism(code, details) {
  const meta = MECHANISM_META[code];
  return {
    code,
    name: meta.name,
    source: meta.source,
    status: STATUS.NOT_RELEVANT,
    confidence: "baixa",
    effort: "Médio",
    positives: [],
    alerts: [],
    blockers: [],
    estimate: null,
    nextStep: "",
    ...details,
  };
}

function taxConfidence(profile, answers) {
  const high =
    profile.lucroRealConfirmed &&
    answers.lucro_ou_imposto === "sim" &&
    answers.maturidade_contabil === "com_clareza" &&
    answers.maturidade_documental === "bem_organizado";

  if (high) return "alta";

  if (
    answers.regime_tributario === "nao_sei" ||
    ["nao_sei", "validar_contador"].includes(answers.lucro_ou_imposto) ||
    profile.documentRisk === "alto"
  ) {
    return "baixa";
  }

  return "media";
}

function documentRiskLabel(risk) {
  return risk === "baixo" ? "Baixo" : risk === "alto" ? "Alto" : "Médio";
}

function fitLevelFromStage(profile, answers) {
  if (!profile.innovationPositive) return "baixo";
  if (answers.estagio_projeto === "prototipo" || answers.estagio_projeto === "escalar") {
    return profile.regularityPositive ? "alto" : "medio";
  }
  if (answers.estagio_projeto === "ideia" || answers.estagio_projeto === "mercado") return "medio";
  return "baixo";
}

function deriveProfile(answers = {}) {
  const activities = list(answers.atividades_inovacao);
  const formalInnovation = activities.some((activity) => FORMAL_INNOVATION.has(activity));
  const needsInformalCheck = activities.includes("nenhuma") || activities.includes("nao_sei");
  const informalInnovation = ["com_frequencia", "as_vezes"].includes(answers.inovacao_informal);
  const innovationPositive = formalInnovation || informalInnovation;
  const waitingForInformalCheck = needsInformalCheck && !answers.inovacao_informal;
  const noInnovationPath = needsInformalCheck && Boolean(answers.inovacao_informal) && !innovationPositive;
  const regularityPositive = ["sim", "parcelamento_em_dia"].includes(answers.regularidade_fiscal);
  const fiscalUnknown = answers.regularidade_fiscal === "nao_sei";
  const lucroRealConfirmed = answers.regime_tributario === "lucro_real";
  const lucroRealPossible = ["lucro_real", "nao_sei"].includes(answers.regime_tributario);
  const taxMonetization = answers.lucro_ou_imposto === "sim" && regularityPositive;
  const ticIndicator =
    ["tecnologia_software", "eletronicos_hardware", "semicondutores"].includes(answers.setor) ||
    activities.includes("produto_fisico") ||
    activities.includes("software_proprio");
  const ticPotential = answers.atividade_tic_brasil === "sim" || answers.uso_leitic === "usa_hoje";
  const accountingWeak = ["nao", "nao_sei"].includes(answers.maturidade_contabil);
  const documentationWeak = ["quase_nada", "nao_sei"].includes(answers.maturidade_documental);
  const accountingPartial = answers.maturidade_contabil === "mais_ou_menos";
  const documentationPartial = answers.maturidade_documental === "algumas_evidencias";
  const documentRisk =
    accountingWeak || documentationWeak
      ? "alto"
      : answers.maturidade_contabil === "com_clareza" && answers.maturidade_documental === "bem_organizado"
        ? "baixo"
        : accountingPartial || documentationPartial
          ? "medio"
          : "medio";
  const startupPotential =
    ["ate_360k", "de_360k_48m", "de_48m_16m"].includes(answers.faturamento_faixa) &&
    ["menos_2", "de_2_5", "de_5_10"].includes(answers.tempo_existencia) &&
    innovationPositive;
  const technologyExecution = list(answers.modelo_execucao_tecnologia);
  const technologyOperationPresent = technologyExecution.some((model) =>
    [
      "equipe_clt",
      "profissionais_pj",
      "consultoria_desenvolvimento",
      "servicos_gerenciados",
    ].includes(model),
  );
  const internalCltTechnology = technologyExecution.includes("equipe_clt");
  const contractedPjTechnology = technologyExecution.includes("profissionais_pj");
  const outsourcedTechnology = technologyExecution.some((model) =>
    ["consultoria_desenvolvimento", "servicos_gerenciados"].includes(model),
  );
  const renunciaCandidate =
    lucroRealPossible && RENUNCIA_OBJECTIVES.has(answers.objetivo_principal);

  return {
    activities,
    formalInnovation,
    needsInformalCheck,
    informalInnovation,
    innovationPositive,
    waitingForInformalCheck,
    noInnovationPath,
    regularityPositive,
    fiscalUnknown,
    lucroRealConfirmed,
    lucroRealPossible,
    taxMonetization,
    ticIndicator,
    ticPotential,
    documentRisk,
    startupPotential,
    technologyExecution,
    technologyOperationPresent,
    internalCltTechnology,
    contractedPjTechnology,
    outsourcedTechnology,
    renunciaCandidate,
  };
}

function isQuestionVisible(question, answers, profile = deriveProfile(answers)) {
  if (question.order > 8 && profile.waitingForInformalCheck) return false;
  if (
    question.order > 8 &&
    profile.noInnovationPath &&
    !["renuncia_track", "renuncia_operational_track"].includes(question.condition)
  ) {
    return false;
  }

  switch (question.condition) {
    case "always":
      return true;
    case "needs_informal_check":
      return profile.needsInformalCheck;
    case "innovation_positive":
      return profile.innovationPositive;
    case "leibem_track":
      return profile.innovationPositive && profile.lucroRealPossible;
    case "ict_19a_track":
      return (
        profile.lucroRealPossible &&
        ["sim", "negociando"].includes(answers.projeto_ict)
      );
    case "tic_track":
      return profile.ticIndicator;
    case "renuncia_track":
      return profile.renunciaCandidate;
    case "renuncia_operational_track":
      return (
        profile.renunciaCandidate &&
        ["educacao_pesquisa", "trabalhador_comunidade", "nao_sei"].includes(
          answers.finalidade_renuncia_tecnologia,
        )
      );
    case "funding_track":
      return profile.innovationPositive && FUNDING_OBJECTIVES.has(answers.objetivo_principal);
    case "semiconductor_track":
      return answers.setor === "semicondutores";
    case "automotive_track":
      return answers.setor === "automotivo_mobilidade";
    default:
      return false;
  }
}

function getVisibleQuestions(answers = {}) {
  const profile = deriveProfile(answers);
  return QUESTION_BANK.filter((question) => isQuestionVisible(question, answers, profile));
}

function pruneAnswers(answers = {}) {
  let pruned = { ...answers };

  for (let pass = 0; pass < 4; pass += 1) {
    const visibleIds = new Set(getVisibleQuestions(pruned).map((question) => question.id));
    const next = Object.fromEntries(
      Object.entries(pruned).filter(([key]) => visibleIds.has(key)),
    );

    if (Object.keys(next).length === Object.keys(pruned).length) return next;
    pruned = next;
  }

  return pruned;
}

function getQuestion(questionId) {
  return QUESTION_INDEX[questionId] ?? null;
}

function getAnswerLabel(questionId, answer) {
  const question = getQuestion(questionId);
  if (!question) return "";

  if (Array.isArray(answer)) {
    return answer
      .map((value) => question.options.find((option) => option.value === value)?.label)
      .filter(Boolean)
      .join(", ");
  }

  return question.options.find((option) => option.value === answer)?.label ?? "";
}

function getAnswerRange(answerKey, value) {
  const rangeGroup = RANGE_BY_ANSWER[answerKey];
  if (!rangeGroup || !value || value === "nao_sei") return null;
  return PARAMETERS.ranges[rangeGroup][value] ?? null;
}

function getNextQuestionId(answers, currentQuestionId) {
  const currentOrder = getQuestion(currentQuestionId)?.order ?? 0;
  return getVisibleQuestions(answers).find((question) => question.order > currentOrder)?.id ?? null;
}

function getPreviousQuestionId(answers, currentQuestionId) {
  const currentOrder = getQuestion(currentQuestionId)?.order ?? Number.MAX_SAFE_INTEGER;
  return getVisibleQuestions(answers)
    .filter((question) => question.order < currentOrder)
    .at(-1)?.id ?? null;
}

function evaluateLeiBem(answers, profile) {
  const spendRange = getAnswerRange("gasto_inovacao", answers.gasto_inovacao);
  const potential = profile.lucroRealPossible && profile.innovationPositive && Boolean(spendRange);
  const immediate = profile.lucroRealConfirmed && profile.innovationPositive && profile.taxMonetization && Boolean(spendRange);
  const hasResearcherIncrease = answers.pesquisadores_equipe === "sim_com_aumento";
  const hasIntellectualProperty = ["patente_concedida", "cultivar_registrado"].includes(
    answers.propriedade_intelectual,
  );
  const exclusionRate = Math.min(
    PARAMETERS.leiBem.baseExclusion +
      (hasResearcherIncrease ? PARAMETERS.leiBem.researcherIncreaseHigh : 0) +
      (hasIntellectualProperty ? PARAMETERS.leiBem.intellectualPropertyIncrease : 0),
    PARAMETERS.leiBem.maxExclusion,
  );
  const estimate = moneyEstimate(
    spendRange,
    exclusionRate,
    "Economia fiscal preliminar por ano",
    `Gastos informados em ${spendRange?.label ?? "faixa não informada"}, exclusão configurada de ${(exclusionRate * 100).toFixed(0)}% e alíquota combinada de ${(PARAMETERS.taxRate * 100).toFixed(0)}%.`,
  );
  const confidence = taxConfidence(profile, answers);
  const alerts = [];
  const blockers = [];

  if (!profile.regularityPositive) blockers.push("A regularidade fiscal precisa ser confirmada ou regularizada.");
  if (answers.lucro_ou_imposto !== "sim") alerts.push("A existência de lucro tributável ou imposto a pagar ainda precisa ser confirmada.");
  if (profile.documentRisk !== "baixo") {
    alerts.push(`Organização de gastos e evidências: risco ${documentRiskLabel(profile.documentRisk).toLowerCase()}.`);
  }
  if (profile.ticPotential) {
    alerts.push("Como a empresa atua em tecnologia, a interação entre Lei do Bem e Lei de TICs deve ser validada para evitar dupla contagem.");
  }

  let status = STATUS.NOT_RELEVANT;
  if (answers.uso_leibem === "usa_hoje") status = STATUS.OPTIMIZE;
  else if (immediate) status = STATUS.AVAILABLE;
  else if (potential) status = STATUS.VALIDATE;
  else if (profile.innovationPositive && answers.regime_tributario && !profile.lucroRealConfirmed) status = STATUS.PREPARE;

  return createMechanism("LEIBEM", {
    status,
    confidence,
    effort: profile.documentRisk === "baixo" ? "Baixo" : "Médio",
    estimate,
    positives: unique([
      profile.innovationPositive ? "Há atividades de criação, melhoria ou desenvolvimento identificadas." : "",
      profile.lucroRealConfirmed ? "A empresa informou Lucro Real." : "",
      profile.taxMonetization ? "Há indicação de imposto ou lucro tributável e regularidade mínima." : "",
      hasResearcherIncrease ? "O aumento de equipe pode ampliar a estimativa, sujeito à validação." : "",
      hasIntellectualProperty ? "Patente ou cultivar concedida pode ampliar a estimativa, sujeito à validação." : "",
    ]),
    alerts,
    blockers,
    nextStep:
      status === STATUS.AVAILABLE || status === STATUS.OPTIMIZE
        ? "Mapear projetos e gastos elegíveis por iniciativa, reunir evidências técnicas e validar a apuração com especialista."
        : "Confirmar regime tributário, lucro/imposto e gastos por projeto antes de estimar o aproveitamento final.",
  });
}

function evaluateLeiBemIct(answers, profile) {
  const projectRange = getAnswerRange("valor_projeto_ict", answers.valor_projeto_ict);
  const potential = profile.lucroRealPossible && ["sim", "negociando"].includes(answers.projeto_ict);
  const immediate =
    profile.lucroRealConfirmed &&
    profile.taxMonetization &&
    answers.projeto_ict === "sim" &&
    answers.ict_19a_aprovacao === "sim";
  const estimate = moneyEstimate(
    projectRange,
    PARAMETERS.leiBemIct19A.conservativeExclusion,
    "Economia fiscal preliminar por ano",
    `Estimativa conservadora com exclusão de 50% sobre ${projectRange?.label ?? "a faixa informada"}; a regra aplicável ao projeto deve ser validada formalmente.`,
  );
  const alerts = [];
  if (answers.ict_19a_aprovacao !== "sim") {
    alerts.push("Sem aprovação formal ou portaria confirmada, esta trilha deve ser tratada apenas como potencial.");
  }
  if (!projectRange) alerts.push("O valor do projeto não foi informado; não há estimativa financeira nesta análise.");

  return createMechanism("LEIBEM_ICT_19A", {
    status: immediate ? STATUS.AVAILABLE : potential ? STATUS.VALIDATE : STATUS.NOT_RELEVANT,
    confidence: immediate && answers.ict_19a_aprovacao === "sim" ? "media" : "baixa",
    effort: "Alto",
    estimate,
    positives: unique([
      answers.projeto_ict === "sim" ? "Há um projeto formal com universidade, instituto ou laboratório." : "",
      answers.projeto_ict === "negociando" ? "A empresa já está estruturando uma parceria técnica." : "",
      answers.ict_19a_aprovacao === "sim" ? "Aprovação formal ou portaria foi indicada." : "",
    ]),
    alerts,
    blockers: profile.lucroRealConfirmed ? [] : ["A regra exige tributação pelo Lucro Real."],
    nextStep: "Validar a formalização do projeto, o parceiro executante, a aprovação aplicável e os documentos de execução antes de considerar o benefício.",
  });
}

function evaluateLeiTics(answers, profile) {
  const revenueRange = getAnswerRange("faturamento_tic", answers.faturamento_tic);
  const mapped = answers.ncm_ppb === "ncm_e_ppb";
  let level = "baixo";
  if (["de_5m_50m", "acima_50m"].includes(answers.faturamento_tic)) level = "alto";
  else if (answers.faturamento_tic === "de_500k_5m") level = "medio";

  let status = STATUS.NOT_RELEVANT;
  if (answers.uso_leitic === "usa_hoje") status = STATUS.OPTIMIZE;
  else if (answers.atividade_tic_brasil === "sim" && mapped) status = STATUS.VALIDATE;
  else if (answers.atividade_tic_brasil === "sim") status = STATUS.PREPARE;

  return createMechanism("LEITIC", {
    status,
    confidence: mapped ? "media" : "baixa",
    effort: "Alto",
    estimate:
      status === STATUS.NOT_RELEVANT
        ? null
        : qualitativeEstimate(
            `Potencial ${level}`,
            revenueRange
              ? `A classificação considera faturamento de tecnologia na faixa ${revenueRange.label}. O crédito financeiro depende de produto, NCM, PPB e regras aplicáveis.`
              : "O cálculo do crédito financeiro depende de produto, NCM, PPB e regras aplicáveis.",
          ),
    positives: unique([
      answers.atividade_tic_brasil === "sim" ? "Há indicação de desenvolvimento ou produção de tecnologia no Brasil." : "",
      mapped ? "NCM e PPB foram informados como mapeados." : "",
      answers.uso_leitic === "usa_hoje" ? "A empresa já informou uso do regime." : "",
    ]),
    alerts: unique([
      !mapped && answers.atividade_tic_brasil === "sim" ? "NCM e processo produtivo ainda precisam ser mapeados." : "",
      answers.atividade_tic_brasil === "sim" ? "Esta análise não estima crédito financeiro exato sem validar produto, NCM, PPB e coeficientes aplicáveis." : "",
    ]),
    blockers: [],
    nextStep:
      status === STATUS.OPTIMIZE
        ? "Revisar produtos habilitados, obrigações de PD&I e documentação de uso do regime."
        : "Fazer análise técnica de enquadramento do produto, NCM, PPB e necessidade de habilitação.",
  });
}

function evaluateRenunciaTecnologia(answers, profile) {
  const purpose = answers.finalidade_renuncia_tecnologia;
  const purposeClear = ["educacao_pesquisa", "trabalhador_comunidade"].includes(purpose);
  const operatingProfitRange = getAnswerRange(
    "lucro_operacional_faixa",
    answers.lucro_operacional_faixa,
  );
  const technologyRange = getAnswerRange(
    "gasto_tecnologia_renuncia",
    answers.gasto_tecnologia_renuncia,
  );
  const route =
    purpose === "educacao_pesquisa"
      ? {
          label: "educação, capacitação ou pesquisa em tecnologia",
          limitRate: PARAMETERS.renunciaTecnologia.educationResearchOperatingProfitLimit,
        }
      : purpose === "trabalhador_comunidade"
        ? {
            label: "trabalhadores, dependentes ou comunidade",
            limitRate: PARAMETERS.renunciaTecnologia.workerCommunityOperatingProfitLimit,
          }
        : null;
  const candidate = profile.renunciaCandidate && Boolean(purpose) && purpose !== "nao_avaliar";
  const readyForValidation =
    candidate &&
    profile.lucroRealConfirmed &&
    profile.regularityPositive &&
    purposeClear &&
    profile.technologyOperationPresent &&
    operatingProfitRange &&
    technologyRange;

  let status = STATUS.NOT_RELEVANT;
  if (readyForValidation) status = STATUS.VALIDATE;
  else if (candidate) status = STATUS.PREPARE;

  return createMechanism("RENUCIA_TECNOLOGIA", {
    status,
    confidence: readyForValidation ? "media" : "baixa",
    effort: "Alto",
    estimate: route
      ? renunciaTechnologyEstimate(
          operatingProfitRange,
          technologyRange,
          route.limitRate,
          route.label,
        )
      : null,
    positives: unique([
      profile.lucroRealConfirmed ? "A empresa informou apuração pelo Lucro Real." : "",
      purposeClear ? `Finalidade selecionada: ${route.label}.` : "",
      profile.internalCltTechnology ? "Há equipe interna de tecnologia contratada pela empresa." : "",
      profile.outsourcedTechnology ? "Há fornecedores recorrentes que ajudam a executar a operação de tecnologia." : "",
      profile.regularityPositive ? "A regularidade fiscal foi informada como positiva." : "",
    ]),
    alerts: unique([
      candidate
        ? "A escala informada de tecnologia não se torna elegível automaticamente; a estrutura, a finalidade e os documentos precisam ser validados."
        : "",
      candidate
        ? "Antes de qualquer aproveitamento, valide a entidade beneficiária, o fluxo financeiro, a documentação e a finalidade da operação."
        : "",
      purpose === "trabalhador_comunidade" && profile.contractedPjTechnology
        ? "Profissionais PJ não devem ser classificados automaticamente como empregados para a rota de trabalhadores, dependentes ou comunidade."
        : "",
      purpose === "nao_sei"
        ? "A definição entre a rota de 1,5% e a rota de 2% ainda precisa ser concluída."
        : "",
    ]),
    blockers: unique([
      candidate && !profile.lucroRealConfirmed
        ? "A apuração pelo Lucro Real precisa ser confirmada antes de estruturar a operação."
        : "",
      candidate && !purposeClear ? "A finalidade legal da operação precisa ser definida." : "",
      candidate && !profile.technologyOperationPresent
        ? "A operação de tecnologia precisa ser caracterizada com equipe ou fornecedores envolvidos."
        : "",
      candidate && !operatingProfitRange
        ? "A faixa de lucro operacional é necessária para estimar o teto legal."
        : "",
      candidate && !technologyRange
        ? "A escala anual de equipe e serviços de tecnologia é necessária para a simulação."
        : "",
    ]),
    nextStep:
      status === STATUS.NOT_RELEVANT
        ? "Revisar a prioridade e o regime tributário antes de avaliar esta trilha."
        : "Validar a finalidade legal, o parceiro elegível, o fluxo financeiro e a documentação da operação antes de estruturar a execução em tecnologia.",
  });
}

function evaluateFomento(answers, profile) {
  const fit =
    profile.innovationPositive &&
    ["ideia", "prototipo", "escalar"].includes(answers.estagio_projeto);
  const level = fitLevelFromStage(profile, answers);
  const status = fit
    ? profile.regularityPositive
      ? STATUS.VALIDATE
      : STATUS.PREPARE
    : STATUS.NOT_RELEVANT;

  return createMechanism("FOMENTO_NAOREEMB", {
    status,
    confidence: answers.estagio_projeto === "nao_sei" ? "baixa" : "media",
    effort: "Médio",
    estimate:
      status === STATUS.NOT_RELEVANT
        ? null
        : qualitativeEstimate(`Fit ${level}`, "Editais e chamadas têm critérios, prazos e concorrência próprios. Não há valor garantido nesta etapa."),
    positives: unique([
      fit ? "Há projeto em fase compatível com chamadas de inovação." : "",
      profile.regularityPositive ? "A regularidade fiscal informada favorece a participação em chamadas." : "",
    ]),
    alerts: !profile.regularityPositive ? ["Regularidade fiscal pode impedir ou dificultar a participação em editais."] : [],
    blockers: [],
    nextStep: "Organizar escopo, cronograma, orçamento e documentação da empresa para monitorar chamadas compatíveis.",
  });
}

function evaluateCredit(answers, profile) {
  const fit =
    profile.regularityPositive &&
    ["sim", "talvez"].includes(answers.apetite_divida) &&
    profile.innovationPositive;
  let status = STATUS.NOT_RELEVANT;
  if (fit && ["sim", "talvez"].includes(answers.capacidade_credito)) status = STATUS.VALIDATE;
  else if (answers.apetite_divida === "sim" && !profile.regularityPositive) status = STATUS.PREPARE;

  return createMechanism("CREDITO_SUBSIDIADO", {
    status,
    confidence: answers.capacidade_credito === "sim" ? "media" : "baixa",
    effort: "Médio",
    estimate:
      status === STATUS.NOT_RELEVANT
        ? null
        : qualitativeEstimate("Linha a estruturar", "A economia depende do valor financiado, prazo, garantias, taxa e linha disponível. Não há economia de juros calculada neste diagnóstico."),
    positives: unique([
      ["sim", "talvez"].includes(answers.apetite_divida) ? "A empresa demonstrou abertura para financiamento." : "",
      answers.capacidade_credito === "sim" ? "Há indicação de capacidade de pagamento ou garantias." : "",
    ]),
    alerts: unique([
      !profile.regularityPositive && answers.apetite_divida === "sim" ? "A regularidade fiscal precisa ser tratada antes de buscar crédito subsidiado." : "",
      answers.capacidade_credito === "nao" ? "A capacidade de garantias ou pagamento precisa ser fortalecida." : "",
    ]),
    blockers: [],
    nextStep: "Validar regularidade, capacidade de pagamento, garantias e o projeto que será financiado antes de comparar linhas.",
  });
}

function evaluateEmbrapii(answers, profile) {
  const fit =
    profile.innovationPositive &&
    ["sim", "talvez"].includes(answers.aceita_ict_coexecucao) &&
    ["prototipo", "escalar", "mercado"].includes(answers.estagio_projeto);

  return createMechanism("EMBRAPII", {
    status: fit ? STATUS.VALIDATE : STATUS.NOT_RELEVANT,
    confidence: fit ? "media" : "baixa",
    effort: "Médio",
    estimate:
      fit
        ? qualitativeEstimate("Fit para cofinanciamento", "O percentual de apoio depende da unidade credenciada, do projeto e da negociação; não é benefício garantido.")
        : null,
    positives: unique([
      fit ? "O projeto está em etapa compatível com desenvolvimento colaborativo." : "",
      answers.aceita_ict_coexecucao === "sim" ? "A empresa aceita coexecutar com parceiro técnico." : "",
    ]),
    alerts: [],
    blockers: [],
    nextStep: "Selecionar uma unidade credenciada compatível e preparar uma conversa técnica sobre escopo, contrapartida e cronograma.",
  });
}

function evaluateStartup(answers, profile) {
  const recommendEquity = profile.startupPotential && ["sim", "talvez"].includes(answers.apetite_equity);
  let status = STATUS.NOT_RELEVANT;
  if (recommendEquity) status = STATUS.VALIDATE;
  else if (profile.startupPotential) status = STATUS.PREPARE;

  return createMechanism("STARTUPLC182", {
    status,
    confidence: profile.startupPotential ? "media" : "baixa",
    effort: "Médio",
    estimate:
      status === STATUS.NOT_RELEVANT
        ? null
        : qualitativeEstimate("Fit de estruturação", "Não é um benefício fiscal direto. Pode apoiar captação, investimento, ambiente regulatório e contratação pública inovadora."),
    positives: unique([
      profile.startupPotential ? "Porte, tempo de existência e inovação indicam potencial de enquadramento inicial." : "",
      ["sim", "talvez"].includes(answers.apetite_equity) ? "Há abertura para avaliar capital externo." : "",
    ]),
    alerts: [],
    blockers: [],
    nextStep: "Organizar tese de crescimento, cap table, materiais de captação e evidências de inovação para avaliar oportunidades de investimento.",
  });
}

function evaluatePadis(answers) {
  const potential = answers.setor === "semicondutores" && ["sim", "nao_sei"].includes(answers.atua_semicondutores);
  return createMechanism("PADIS", {
    status: potential ? STATUS.VALIDATE : STATUS.NOT_RELEVANT,
    confidence: "baixa",
    effort: "Alto",
    estimate: potential ? qualitativeEstimate("Oportunidade setorial", "A análise de PADIS exige avaliação específica do produto, processo e requisitos vigentes.") : null,
    positives: potential ? ["Há indicação de atuação na cadeia de semicondutores ou displays."] : [],
    alerts: [],
    blockers: [],
    nextStep: "Fazer uma análise setorial específica antes de considerar esta oportunidade.",
  });
}

function evaluateRota2030(answers) {
  const potential = answers.setor === "automotivo_mobilidade" && ["sim", "nao_sei"].includes(answers.atua_rota2030);
  return createMechanism("ROTA2030", {
    status: potential ? STATUS.VALIDATE : STATUS.NOT_RELEVANT,
    confidence: "baixa",
    effort: "Alto",
    estimate: potential ? qualitativeEstimate("Oportunidade setorial", "A análise de Rota 2030 exige avaliação específica da atividade e dos requisitos vigentes.") : null,
    positives: potential ? ["Há indicação de atuação em mobilidade com desenvolvimento tecnológico."] : [],
    alerts: [],
    blockers: [],
    nextStep: "Fazer uma análise setorial específica antes de considerar esta oportunidade.",
  });
}

function valueScore(result) {
  if (result.estimate?.kind === "financial") {
    const reference = result.estimate.max ?? result.estimate.min;
    if (reference >= 300000) return 35;
    if (reference >= 50000) return 27;
    if (reference >= 10000) return 16;
    return 8;
  }

  const label = result.estimate?.label?.toLowerCase() ?? "";
  if (label.includes("alto")) return 24;
  if (label.includes("médio") || label.includes("medio")) return 15;
  if (result.estimate) return 8;
  return 0;
}

function alignmentScore(code, objective) {
  const priorities = OBJECTIVE_PRIORITIES[objective] ?? [];
  if (priorities.length === 0) return 12;
  const index = priorities.indexOf(code);
  if (index === 0) return 25;
  if (index > 0) return Math.max(10, 19 - index * 3);
  return 4;
}

function easeScore(result, profile, answers) {
  let score = profile.documentRisk === "baixo" ? 20 : profile.documentRisk === "medio" ? 10 : 0;
  if (result.code === "CREDITO_SUBSIDIADO" && answers.capacidade_credito === "nao") score -= 8;
  if (result.code === "EMBRAPII" && answers.aceita_ict_coexecucao === "talvez") score -= 4;
  if (result.code === "RENUCIA_TECNOLOGIA" && !profile.technologyOperationPresent) score -= 8;
  if (["LEITIC", "LEIBEM_ICT_19A", "PADIS", "ROTA2030"].includes(result.code)) score -= 4;
  return Math.max(0, score);
}

function urgencyScore(status) {
  if (status === STATUS.AVAILABLE || status === STATUS.OPTIMIZE) return 10;
  if (status === STATUS.VALIDATE) return 7;
  if (status === STATUS.PREPARE) return 3;
  return 0;
}

function confidenceScore(confidence) {
  return confidence === "alta" ? 10 : confidence === "media" ? 6 : 2;
}

function riskPenalty(result, profile, answers) {
  let penalty = 0;
  if (profile.fiscalUnknown) penalty += 10;
  if (profile.documentRisk === "alto") penalty += 10;
  if (["nao", "nao_sei"].includes(answers.maturidade_contabil)) penalty += 10;
  if (
    result.code === "LEIBEM" &&
    result.alerts.some((alert) => alert.includes("interação entre Lei do Bem e Lei de TICs"))
  ) {
    penalty += 15;
  }
  if (result.code === "LEITIC" && !["ncm_e_ppb", undefined].includes(answers.ncm_ppb)) penalty += 15;
  if (result.code === "RENUCIA_TECNOLOGIA" && answers.finalidade_renuncia_tecnologia === "nao_sei") penalty += 10;
  if (result.code === "RENUCIA_TECNOLOGIA" && list(answers.modelo_execucao_tecnologia).includes("nao_sei")) penalty += 10;
  if (answers.regularidade_fiscal === "nao") penalty += 20;
  return penalty;
}

function scoreMechanism(result, profile, answers) {
  if (result.status === STATUS.NOT_RELEVANT || result.status === STATUS.BLOCKED) {
    return { total: -1, parts: {} };
  }

  const parts = {
    value: valueScore(result),
    alignment: alignmentScore(result.code, answers.objetivo_principal),
    ease: easeScore(result, profile, answers),
    urgency: urgencyScore(result.status),
    confidence: confidenceScore(result.confidence),
    risk: riskPenalty(result, profile, answers),
  };

  return {
    total: Math.max(0, parts.value + parts.alignment + parts.ease + parts.urgency + parts.confidence - parts.risk),
    parts,
  };
}

function rankMechanisms(mechanisms, profile, answers) {
  return mechanisms
    .map((mechanism) => {
      const score = scoreMechanism(mechanism, profile, answers);
      return { ...mechanism, score: score.total, scoreParts: score.parts };
    })
    .sort((left, right) => right.score - left.score || left.name.localeCompare(right.name, "pt-BR"));
}

function recommendationCopy(primary, profile) {
  if (!primary) {
    return {
      heading: "Não encontramos uma oportunidade imediata com os dados informados.",
      body: "O diagnóstico pode ser retomado quando houver mais informação fiscal, técnica ou de projeto.",
    };
  }

  const statusCopy = STATUS_COPY[primary.status].label.toLowerCase();
  const technicalSignal = profile.innovationPositive
    ? "Há sinais de atividades de criação, melhoria ou desenvolvimento na empresa."
    : "";

  return {
    heading: `${primary.name} é a prioridade mais promissora agora.`,
    body: `${technicalSignal} Pelas respostas, esta trilha ${statusCopy}. ${primary.nextStep}`,
  };
}

function evaluateDiagnostic(answers = {}) {
  const profile = deriveProfile(answers);
  const renunciaTecnologia = evaluateRenunciaTecnologia(answers, profile);

  if (profile.noInnovationPath && renunciaTecnologia.status === STATUS.NOT_RELEVANT) {
    return {
      profile,
      noInnovation: true,
      mechanisms: [],
      mainOpportunities: [],
      preparations: [],
      alerts: [],
      recommendation: {
        heading: "Ainda não identificamos uma atividade clara de inovação.",
        body: "Isso não significa que a empresa não tenha oportunidade. Muitas empresas melhoram produtos, processos ou atendimento sem chamar isso de inovação. O próximo passo é revisar essas iniciativas com as áreas técnicas e operacionais.",
      },
    };
  }

  const mechanisms = [
    evaluateLeiBem(answers, profile),
    evaluateLeiBemIct(answers, profile),
    evaluateLeiTics(answers, profile),
    renunciaTecnologia,
    evaluateFomento(answers, profile),
    evaluateCredit(answers, profile),
    evaluateEmbrapii(answers, profile),
    evaluateStartup(answers, profile),
    evaluatePadis(answers),
    evaluateRota2030(answers),
  ];
  const ranked = rankMechanisms(mechanisms, profile, answers);
  const mainOpportunities = ranked.filter((mechanism) => INSTANT_STATUSES.has(mechanism.status)).slice(0, 3);
  const preparations = ranked.filter((mechanism) => mechanism.status === STATUS.PREPARE).slice(0, 4);
  const alerts = unique(
    ranked
      .filter((mechanism) => mechanism.status !== STATUS.NOT_RELEVANT)
      .flatMap((mechanism) => mechanism.alerts)
      .slice(0, 5),
  );
  const primary = mainOpportunities[0] ?? preparations[0] ?? null;

  return {
    profile,
    noInnovation: false,
    mechanisms: ranked,
    mainOpportunities,
    preparations,
    alerts,
    recommendation: recommendationCopy(primary, profile),
  };
}

function buildProfileSummary(answers, profile = deriveProfile(answers)) {
  const sector = getAnswerLabel("setor", answers.setor) || "Atuação a confirmar";
  const regimeByAnswer = {
    lucro_real: {
      value: "Lucro Real",
      detail: "Permite avaliar incentivos fiscais específicos.",
    },
    lucro_presumido: {
      value: "Lucro Presumido",
      detail: "Algumas trilhas fiscais não se aplicam neste regime.",
    },
    simples_nacional: {
      value: "Simples Nacional",
      detail: "A leitura fiscal considera o regime simplificado.",
    },
    nao_sei: {
      value: "Regime a confirmar",
      detail: "As simulações fiscais seguem uma leitura conservadora.",
    },
  };
  const objectiveByAnswer = {
    reduzir_impostos: {
      value: "Reduzir carga tributária",
      detail: "Priorizamos caminhos de eficiência fiscal.",
    },
    buscar_funding: {
      value: "Buscar recursos",
      detail: "Priorizamos fomento e alternativas de capital.",
    },
    financiar_expansao: {
      value: "Financiar crescimento",
      detail: "Combinamos crédito e eficiência fiscal quando cabível.",
    },
    atrair_investidor: {
      value: "Avaliar capital externo",
      detail: "Priorizamos sinais de estrutura e investimento.",
    },
    apoiar_projetos: {
      value: "Gerar impacto com tecnologia",
      detail: "Avaliamos a finalidade e a estrutura da operação.",
    },
    nao_sei: {
      value: "Foco em exploração",
      detail: "Mantemos os caminhos que ainda podem fazer sentido.",
    },
  };
  const regime = regimeByAnswer[answers.regime_tributario] ?? regimeByAnswer.nao_sei;
  const objective = objectiveByAnswer[answers.objetivo_principal] ?? objectiveByAnswer.nao_sei;
  const signals = [
    {
      label: "Atuação principal",
      value: sector,
      detail: "Setor que orienta as oportunidades.",
    },
    {
      label: "Tributação atual",
      value: regime.value,
      detail: regime.detail,
    },
    {
      label: "Momento da decisão",
      value: objective.value,
      detail: objective.detail,
    },
  ];
  const innovation = profile.innovationPositive
    ? "Foram identificadas atividades de criação, melhoria ou desenvolvimento."
    : "Não foi identificada atividade de inovação de forma clara.";

  return {
    headline: signals.map((signal) => signal.value).join(" · "),
    signals,
    innovation,
  };
}


const defaultState = () => ({
  answers: {},
  currentQuestionId: "objetivo_principal",
  completed: false,
  updatedAt: null,
});

const elements = {
  diagnosticView: document.getElementById("diagnosticView"),
  resultView: document.getElementById("resultView"),
  questionPanel: document.getElementById("questionPanel"),
  questionIndex: document.getElementById("questionIndex"),
  sectionKicker: document.getElementById("sectionKicker"),
  questionTitle: document.getElementById("questionTitle"),
  questionHelp: document.getElementById("questionHelp"),
  choiceList: document.getElementById("choiceList"),
  continueButton: document.getElementById("continueButton"),
  backButton: document.getElementById("backButton"),
  selectionHint: document.getElementById("selectionHint"),
  stepLabel: document.getElementById("stepLabel"),
  stepName: document.getElementById("stepName"),
  progressFill: document.getElementById("progressFill"),
  progressCount: document.getElementById("progressCount"),
  stepper: document.getElementById("stepper"),
  pathways: document.getElementById("pathways"),
  pathwaysDescription: document.getElementById("pathwaysDescription"),
  timeEstimate: document.getElementById("timeEstimate"),
  sessionLabel: document.getElementById("sessionLabel"),
  saveStatus: document.getElementById("saveStatus"),
  saveButton: document.getElementById("saveButton"),
  toast: document.getElementById("toast"),
  resultTitle: document.getElementById("resultTitle"),
  resultIntro: document.getElementById("resultIntro"),
  profileSignals: document.getElementById("profileSignals"),
  profileInnovation: document.getElementById("profileInnovation"),
  primaryResult: document.getElementById("primaryResult"),
  opportunitiesSection: document.getElementById("opportunitiesSection"),
  opportunityList: document.getElementById("opportunityList"),
  preparationSection: document.getElementById("preparationSection"),
  preparationList: document.getElementById("preparationList"),
  riskPanel: document.getElementById("riskPanel"),
  riskList: document.getElementById("riskList"),
  assumptionsContent: document.getElementById("assumptionsContent"),
  exportButton: document.getElementById("exportButton"),
  printButton: document.getElementById("printButton"),
  restartButton: document.getElementById("restartButton"),
  privacyButton: document.getElementById("privacyButton"),
};

let state = loadState();

function loadState() {
  try {
    const saved = window.localStorage.getItem(APP_META.storageKey);
    if (!saved) return defaultState();

    const parsed = JSON.parse(saved);
    const answers = pruneAnswers(parsed.answers ?? {});
    return {
      ...defaultState(),
      ...parsed,
      answers,
      currentQuestionId: parsed.currentQuestionId ?? "objetivo_principal",
    };
  } catch {
    return defaultState();
  }
}

function persist(showMessage = false) {
  state.updatedAt = new Date().toISOString();

  try {
    window.localStorage.setItem(APP_META.storageKey, JSON.stringify({
      version: APP_META.rulesVersion,
      answers: state.answers,
      currentQuestionId: state.currentQuestionId,
      completed: state.completed,
      updatedAt: state.updatedAt,
    }));
    elements.saveStatus.textContent = "Salvo neste dispositivo";
    if (showMessage) showToast("Progresso salvo neste dispositivo.");
  } catch {
    elements.saveStatus.textContent = "Salvamento indisponível";
    if (showMessage) showToast("Não foi possível salvar neste navegador.");
  }
}

function showToast(message) {
  elements.toast.textContent = message;
  elements.toast.classList.add("is-visible");
  window.clearTimeout(showToast.timeout);
  showToast.timeout = window.setTimeout(() => {
    elements.toast.classList.remove("is-visible");
  }, 3200);
}

function escapeHtml(value = "") {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function formatMoney(value) {
  return new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
    maximumFractionDigits: 0,
  }).format(value);
}

function formatFinancialEstimate(estimate) {
  if (!estimate || estimate.kind !== "financial") return "";
  if (estimate.max === null) return `A partir de ${formatMoney(estimate.min)} por ano`;
  return `Entre ${formatMoney(estimate.min)} e ${formatMoney(estimate.max)} por ano`;
}

function currentQuestion() {
  return getQuestion(state.currentQuestionId);
}

function answerIsPresent(question) {
  const answer = state.answers[question.id];
  return question.type === "multiple" ? Array.isArray(answer) && answer.length > 0 : Boolean(answer);
}

function ensureCurrentQuestion() {
  const visibleQuestions = getVisibleQuestions(state.answers);
  const current = currentQuestion();
  const stillVisible = visibleQuestions.some((question) => question.id === state.currentQuestionId);

  if (stillVisible) return visibleQuestions;

  const currentOrder = current?.order ?? 0;
  state.currentQuestionId =
    visibleQuestions.find((question) => question.order >= currentOrder)?.id ??
    visibleQuestions.at(-1)?.id ??
    "objetivo_principal";
  return visibleQuestions;
}

function getStage(question) {
  return STEPS.find((step) => step.id === question.stage) ?? STEPS[0];
}

function renderProgress(visibleQuestions, question) {
  const currentIndex = Math.max(0, visibleQuestions.findIndex((item) => item.id === question.id));
  const stage = getStage(question);
  const stageProgress = (stage.id / STEPS.length) * 100;

  elements.stepLabel.textContent = `Etapa ${stage.id} de ${STEPS.length}`;
  elements.stepName.textContent = stage.name;
  elements.progressCount.textContent = `Questão ${currentIndex + 1} de ${visibleQuestions.length}`;
  elements.progressFill.style.width = `${stageProgress}%`;
  elements.stepper.innerHTML = STEPS.map((item) => {
    const status = item.id === stage.id ? "active" : item.id < stage.id ? "complete" : "";
    return `<li class="${status}" aria-label="Etapa ${item.id}: ${escapeHtml(item.name)}"></li>`;
  }).join("");
}

function renderChoices(question) {
  const selected = state.answers[question.id] ?? (question.type === "multiple" ? [] : null);
  const isMultiple = question.type === "multiple";
  elements.choiceList.setAttribute("role", isMultiple ? "group" : "radiogroup");
  elements.choiceList.setAttribute("aria-label", question.title);
  elements.choiceList.classList.toggle("is-multiple", isMultiple);

  elements.choiceList.innerHTML = question.options
    .map((option) => {
      const isSelected = isMultiple ? selected.includes(option.value) : selected === option.value;
      const role = isMultiple ? "checkbox" : "radio";
      return `
        <button
          class="choice-card"
          data-value="${escapeHtml(option.value)}"
          data-tone="${escapeHtml(option.tone)}"
          type="button"
          role="${role}"
          aria-checked="${isSelected}"
        >
          <span class="choice-symbol" aria-hidden="true">${escapeHtml(option.symbol)}</span>
          <span class="choice-copy">
            <span class="choice-title">${escapeHtml(option.label)}</span>
            <span class="choice-detail">${escapeHtml(option.detail)}</span>
          </span>
          <span class="choice-indicator" aria-hidden="true"></span>
        </button>
      `;
    })
    .join("");
}

function candidateCodes() {
  const profile = deriveProfile(state.answers);
  const objectiveCodes = OBJECTIVE_PRIORITIES[state.answers.objetivo_principal] ?? [];
  const codes = objectiveCodes.length
    ? [...objectiveCodes]
    : ["LEIBEM", "FOMENTO_NAOREEMB", "CREDITO_SUBSIDIADO", "LEITIC"];

  if (profile.innovationPositive) codes.push("LEIBEM", "FOMENTO_NAOREEMB", "EMBRAPII");
  if (profile.ticIndicator) codes.push("LEITIC");
  if (profile.startupPotential) codes.push("STARTUPLC182");
  if (profile.renunciaCandidate) codes.push("RENUCIA_TECNOLOGIA");

  return [...new Set(codes)].slice(0, 5);
}

function renderPathways(visibleQuestions) {
  const diagnostic = evaluateDiagnostic(state.answers);
  const resultsByCode = Object.fromEntries(
    diagnostic.mechanisms.map((mechanism) => [mechanism.code, mechanism]),
  );
  const candidates = candidateCodes();
  const question = currentQuestion();
  const remainingQuestions = Math.max(0, visibleQuestions.length - visibleQuestions.findIndex((item) => item.id === question.id) - 1);
  const minutes = remainingQuestions <= 5 ? "2 a 4 minutos" : remainingQuestions <= 11 ? "4 a 6 minutos" : "6 a 8 minutos";

  elements.pathways.innerHTML = candidates
    .map((code, index) => {
      const result = resultsByCode[code];
      const copy = result && result.status !== STATUS.NOT_RELEVANT ? STATUS_COPY[result.status] : null;
      const label = copy ? copy.label : "Em análise";
      const className = copy ? `is-${copy.tone}` : index === 0 ? "is-priority" : "";
      return `
        <div class="pathway ${className}">
          <span class="pathway-label">${escapeHtml(MECHANISM_META[code].name)}</span>
          <span class="pathway-badge">${escapeHtml(label)}</span>
        </div>
      `;
    })
    .join("");

  elements.pathwaysDescription.textContent = state.answers.objetivo_principal
    ? "Conforme avançamos, removemos os caminhos que não fazem sentido para a empresa."
    : "Sua primeira resposta organiza o diagnóstico pelas oportunidades mais relevantes.";
  elements.timeEstimate.textContent = minutes;
}

function renderQuestion(animate = false) {
  const visibleQuestions = ensureCurrentQuestion();
  const question = currentQuestion();
  if (!question) return;

  state.completed = false;
  elements.diagnosticView.hidden = false;
  elements.resultView.hidden = true;
  elements.questionIndex.textContent = String(question.order).padStart(2, "0");
  elements.sectionKicker.textContent = question.section;
  elements.questionTitle.textContent = question.title;
  elements.questionHelp.textContent = question.help;
  elements.sessionLabel.textContent = "Diagnóstico em andamento";

  renderProgress(visibleQuestions, question);
  renderChoices(question);
  renderPathways(visibleQuestions);

  const hasAnswer = answerIsPresent(question);
  const previousQuestionId = getPreviousQuestionId(state.answers, question.id);
  elements.continueButton.disabled = !hasAnswer;
  elements.backButton.disabled = !previousQuestionId;
  elements.selectionHint.textContent = hasAnswer
    ? question.type === "multiple"
      ? "Seleções registradas"
      : "Seleção registrada"
    : question.type === "multiple"
      ? "Selecione uma ou mais opções para continuar"
      : "Selecione uma opção para continuar";
  elements.selectionHint.classList.toggle("is-ready", hasAnswer);

  if (animate) {
    elements.questionPanel.classList.remove("is-changing");
    window.requestAnimationFrame(() => elements.questionPanel.classList.add("is-changing"));
  }
}

function selectAnswer(value) {
  const question = currentQuestion();
  if (!question) return;

  if (question.type === "multiple") {
    const selected = Array.isArray(state.answers[question.id]) ? [...state.answers[question.id]] : [];
    const exclusiveValues = question.exclusiveValues ?? [];
    const isExclusive = exclusiveValues.includes(value);
    let next;

    if (isExclusive) {
      next = selected.includes(value) ? [] : [value];
    } else if (selected.includes(value)) {
      next = selected.filter((item) => item !== value);
    } else {
      next = [...selected.filter((item) => !exclusiveValues.includes(item)), value];
    }

    state.answers[question.id] = next;
  } else {
    state.answers[question.id] = value;
  }

  state.answers = pruneAnswers(state.answers);
  persist();
  renderQuestion();
  window.requestAnimationFrame(() => {
    const selectedChoice = [...elements.choiceList.querySelectorAll(".choice-card")]
      .find((card) => card.dataset.value === value);
    selectedChoice?.focus();
  });
}

function continueDiagnostic() {
  const question = currentQuestion();
  if (!question || !answerIsPresent(question)) {
    showToast("Selecione uma resposta para continuar.");
    return;
  }

  state.answers = pruneAnswers(state.answers);
  const nextQuestionId = getNextQuestionId(state.answers, question.id);

  if (!nextQuestionId) {
    state.completed = true;
    persist();
    renderResult();
    window.requestAnimationFrame(() => elements.resultTitle.focus());
    return;
  }

  state.currentQuestionId = nextQuestionId;
  persist();
  renderQuestion(true);
  window.requestAnimationFrame(() => elements.questionTitle.focus());
}

function goBack() {
  const previousQuestionId = getPreviousQuestionId(state.answers, state.currentQuestionId);
  if (!previousQuestionId) return;

  state.currentQuestionId = previousQuestionId;
  persist();
  renderQuestion(true);
  window.requestAnimationFrame(() => elements.questionTitle.focus());
}

function priorityLabel(score) {
  if (score >= 70) return "Prioridade alta";
  if (score >= 40) return "Prioridade relevante";
  return "Oportunidade em evolução";
}

function renderEstimate(estimate) {
  if (!estimate) return "";

  if (estimate.kind === "financial") {
    return `
      <div class="estimate-block">
        <span class="estimate-label">${escapeHtml(estimate.label)}</span>
        <strong>${escapeHtml(formatFinancialEstimate(estimate))}</strong>
      </div>
    `;
  }

  return `
    <div class="estimate-block qualitative">
      <span class="estimate-label">${escapeHtml(estimate.label)}</span>
      <strong>${escapeHtml(estimate.detail)}</strong>
    </div>
  `;
}

function renderBullets(items, className) {
  if (!items?.length) return "";
  return `<ul class="${className}">${items.slice(0, 3).map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>`;
}

function renderMechanismCard(mechanism) {
  const status = STATUS_COPY[mechanism.status];
  const source = mechanism.source
    ? `<a class="source-link" href="${escapeHtml(mechanism.source.url)}" target="_blank" rel="noreferrer">${escapeHtml(mechanism.source.label)}</a>`
    : "";
  const nextStep = mechanism.nextStep
    ? `<p class="next-step"><span>Próximo passo</span>${escapeHtml(mechanism.nextStep)}</p>`
    : "";

  return `
    <article class="opportunity-card">
      <div class="opportunity-topline">
        <span class="status-badge ${escapeHtml(status.tone)}">${escapeHtml(status.label)}</span>
        <span class="priority-chip">${escapeHtml(priorityLabel(mechanism.score))}</span>
      </div>
      <h3>${escapeHtml(mechanism.name)}</h3>
      ${renderEstimate(mechanism.estimate)}
      ${renderBullets(mechanism.positives, "evidence-list")}
      ${renderBullets(mechanism.alerts, "alert-list")}
      ${nextStep}
      ${source ? `<div class="source-row">${source}</div>` : ""}
    </article>
  `;
}

function renderPrimaryResult(diagnostic) {
  if (diagnostic.noInnovation) {
    elements.primaryResult.innerHTML = `
      <div class="primary-result-copy alternate-result">
        <p class="section-kicker">LEITURA INICIAL</p>
        <h2>${escapeHtml(diagnostic.recommendation.heading)}</h2>
        <p>${escapeHtml(diagnostic.recommendation.body)}</p>
        <p class="primary-next"><span>Próximo passo</span>Reunir as áreas de operação, produto e tecnologia para mapear melhorias, testes e iniciativas que ainda não estão nomeadas ou documentadas.</p>
      </div>
    `;
    return;
  }

  const primary = diagnostic.mainOpportunities[0] ?? diagnostic.preparations[0];
  const status = primary ? STATUS_COPY[primary.status] : null;
  const metric = primary?.estimate ? renderEstimate(primary.estimate) : "";
  const source = primary?.source
    ? `<a class="source-link" href="${escapeHtml(primary.source.url)}" target="_blank" rel="noreferrer">${escapeHtml(primary.source.label)}</a>`
    : "";

  elements.primaryResult.innerHTML = `
    <div class="primary-result-copy">
      <p class="section-kicker">MELHOR CAMINHO AGORA</p>
      <h2>${escapeHtml(diagnostic.recommendation.heading)}</h2>
      <p>${escapeHtml(diagnostic.recommendation.body)}</p>
      ${primary ? `<span class="status-badge ${escapeHtml(status.tone)}">${escapeHtml(status.label)}</span>` : ""}
      ${source ? `<div class="source-row">${source}</div>` : ""}
    </div>
    <div class="primary-result-metric">
      ${metric || `<div class="estimate-block qualitative"><span class="estimate-label">Leitura atual</span><strong>Há pontos a estruturar antes de estimar valor financeiro.</strong></div>`}
      ${primary ? `<p class="confidence-note">Confiança da leitura: <strong>${escapeHtml(primary.confidence)}</strong></p>` : ""}
    </div>
  `;
}

function renderOpportunities(diagnostic) {
  if (diagnostic.noInnovation) {
    elements.opportunitiesSection.hidden = true;
    return;
  }

  elements.opportunitiesSection.hidden = false;
  if (!diagnostic.mainOpportunities.length) {
    elements.opportunityList.innerHTML = `
      <div class="empty-result">
        <strong>Não há uma oportunidade pronta para avançar ainda.</strong>
        <span>Veja abaixo os caminhos que podem ser preparados com os dados atuais.</span>
      </div>
    `;
    return;
  }

  elements.opportunityList.innerHTML = diagnostic.mainOpportunities
    .map(renderMechanismCard)
    .join("");
}

function renderPreparations(diagnostic) {
  if (diagnostic.noInnovation || !diagnostic.preparations.length) {
    elements.preparationSection.hidden = true;
    return;
  }

  elements.preparationSection.hidden = false;
  elements.preparationList.innerHTML = diagnostic.preparations
    .map((mechanism) => `
      <article class="preparation-item">
        <div>
          <h3>${escapeHtml(mechanism.name)}</h3>
          <p>${escapeHtml(mechanism.nextStep)}</p>
        </div>
        <span class="compact-status">Preparar</span>
      </article>
    `)
    .join("");
}

function renderRisks(diagnostic) {
  const profile = diagnostic.profile;
  const risks = [...diagnostic.alerts];

  if (!diagnostic.noInnovation && profile.documentRisk !== "baixo") {
    risks.unshift(`A organização de evidências e gastos está com risco ${profile.documentRisk}; isso reduz a confiança de benefícios fiscais.`);
  }
  if (state.answers.regularidade_fiscal === "nao") {
    risks.unshift("Há indicação de pendência fiscal. Isso pode bloquear incentivos e dificultar editais ou crédito.");
  }
  if (!risks.length) {
    risks.push("As informações indicam boa base inicial. Ainda assim, a documentação técnica, fiscal e contábil deve ser validada antes de qualquer aproveitamento.");
  }

  elements.riskPanel.hidden = false;
  elements.riskList.innerHTML = [...new Set(risks)].slice(0, 5)
    .map((risk) => `<p class="risk-item"><span aria-hidden="true">!</span>${escapeHtml(risk)}</p>`)
    .join("");
}

function renderAssumptions(diagnostic) {
  const financialMechanisms = diagnostic.mechanisms.filter(
    (mechanism) => mechanism.estimate?.kind === "financial",
  );
  const premiseList = financialMechanisms.length
    ? financialMechanisms
        .map((mechanism) => `<li><strong>${escapeHtml(mechanism.name)}:</strong> ${escapeHtml(mechanism.estimate.premise)}</li>`)
        .join("")
    : "<li>Nenhuma estimativa financeira foi exibida porque faltam dados, não há imposto a monetizar agora ou a oportunidade é qualitativa.</li>";

  elements.assumptionsContent.innerHTML = `
    <p>Este resultado é uma estimativa preliminar baseada nas respostas informadas e na versão ${escapeHtml(APP_META.rulesVersion)} das regras.</p>
    <ul>${premiseList}</ul>
    <p>Na Lei do Bem, o cálculo usa alíquota combinada de ${(PARAMETERS.taxRate * 100).toFixed(0)}% e percentuais configuráveis de exclusão. Na Renúncia Fiscal em Tecnologia, a estimativa usa o menor valor entre a escala de tecnologia e o teto de 1,5% ou 2% do lucro operacional, simulando IRPJ, adicional e CSLL. A finalidade, a entidade, o fluxo financeiro e os documentos precisam ser validados antes de qualquer aproveitamento.</p>
    <p>Antes de usar qualquer incentivo, valide as informações com especialistas fiscal, contábil e jurídico e com a documentação da empresa.</p>
  `;
}

function renderResult() {
  const diagnostic = evaluateDiagnostic(state.answers);
  const profileSummary = buildProfileSummary(state.answers, diagnostic.profile);

  elements.diagnosticView.hidden = true;
  elements.resultView.hidden = false;
  elements.sessionLabel.textContent = "Resultado disponível";
  elements.resultIntro.textContent = diagnostic.noInnovation
    ? "O diagnóstico encontrou uma oportunidade de investigação antes de recomendar incentivos específicos."
    : "Organizamos as oportunidades por relevância, potencial financeiro, esforço e confiança das informações.";
  elements.profileSignals.innerHTML = profileSummary.signals
    .map(
      (signal) => `
        <div class="profile-signal">
          <span class="profile-signal-label">${escapeHtml(signal.label)}</span>
          <strong class="profile-signal-value">${escapeHtml(signal.value)}</strong>
          <span class="profile-signal-detail">${escapeHtml(signal.detail)}</span>
        </div>
      `,
    )
    .join("");
  elements.profileInnovation.textContent = profileSummary.innovation;

  renderPrimaryResult(diagnostic);
  renderOpportunities(diagnostic);
  renderPreparations(diagnostic);
  renderRisks(diagnostic);
  renderAssumptions(diagnostic);
}

function buildExportText() {
  const diagnostic = evaluateDiagnostic(state.answers);
  const profileSummary = buildProfileSummary(state.answers, diagnostic.profile);
  const lines = [
    "MONYU | DIAGNÓSTICO DE INCENTIVOS E FUNDING",
    `Data: ${new Intl.DateTimeFormat("pt-BR").format(new Date())}`,
    `Versão das regras: ${APP_META.rulesVersion}`,
    "",
    "PERFIL IDENTIFICADO",
    ...profileSummary.signals.map((signal) => `${signal.label}: ${signal.value}`),
    profileSummary.innovation,
    "",
    "RECOMENDAÇÃO PRINCIPAL",
    diagnostic.recommendation.heading,
    diagnostic.recommendation.body,
    "",
  ];

  if (diagnostic.noInnovation) {
    lines.push("PRÓXIMO PASSO", "Mapear melhorias, testes e iniciativas de criação com as áreas técnicas e operacionais.");
  } else {
    lines.push("OPORTUNIDADES PRIORITÁRIAS");
    diagnostic.mainOpportunities.forEach((mechanism) => {
      lines.push(`- ${mechanism.name}: ${STATUS_COPY[mechanism.status].label}`);
      if (mechanism.estimate?.kind === "financial") lines.push(`  ${formatFinancialEstimate(mechanism.estimate)}`);
      if (mechanism.estimate?.kind === "qualitative") lines.push(`  ${mechanism.estimate.label}: ${mechanism.estimate.detail}`);
      lines.push(`  Próximo passo: ${mechanism.nextStep}`);
    });

    if (diagnostic.preparations.length) {
      lines.push("", "CAMINHOS A PREPARAR");
      diagnostic.preparations.forEach((mechanism) => lines.push(`- ${mechanism.name}: ${mechanism.nextStep}`));
    }
  }

  lines.push(
    "",
    "AVISO",
    "Este resultado é uma estimativa preliminar e não substitui análise fiscal, contábil ou jurídica.",
  );
  return lines.join("\n");
}

function exportResult() {
  const blob = new Blob([buildExportText()], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = "diagnostico-monyu-incentivos.txt";
  document.body.appendChild(link);
  link.click();
  link.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 0);
  showToast("Resumo exportado.");
}

function restartDiagnostic() {
  const shouldRestart = window.confirm("Começar uma nova análise? As respostas salvas neste dispositivo serão substituídas.");
  if (!shouldRestart) return;

  state = defaultState();
  try {
    window.localStorage.removeItem(APP_META.storageKey);
  } catch {
    // The new in-memory session remains usable even when storage is unavailable.
  }
  renderQuestion(true);
  window.requestAnimationFrame(() => elements.questionTitle.focus());
  showToast("Nova análise iniciada.");
}

elements.choiceList.addEventListener("click", (event) => {
  const card = event.target.closest(".choice-card");
  if (!card) return;
  selectAnswer(card.dataset.value);
});

elements.continueButton.addEventListener("click", continueDiagnostic);
elements.backButton.addEventListener("click", goBack);
elements.saveButton.addEventListener("click", () => persist(true));
elements.exportButton.addEventListener("click", exportResult);
elements.printButton.addEventListener("click", () => window.print());
elements.restartButton.addEventListener("click", restartDiagnostic);
elements.privacyButton.addEventListener("click", () => {
  showToast("As respostas ficam apenas neste navegador. Esta versão não envia dados para um servidor.");
});

if (state.completed) renderResult();
else renderQuestion();
